### ISSUE TITLE
[bug] VA-radio web component ignoring keyboard

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/vets-design-system-documentation#1096]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

When using the `VaRadio` web component, the `onRadioOptionSelected` and `onVaValueChange` callbacks are not called while using the keyboard to interact with the radio buttons.

## What I expected to happen

The `onRadioOptionSelected` and `onVaValueChange` (both?) callbacks should be called when the radio selection has changed

## Reproducing
- Formation version: 11.3.2 (component-library)
- Device: (e.g. iPhone 8, Macbook): Macbook (any)
- Browser: (e.g. Firefox, IE 11): Chrome (any)

Steps to reproduce:

1. Go to [Code sandbox demo](https://codesandbox.io/s/fervent-butterfly-dhzkwu?file=/src/App.js)
2. Mouse click to select an option - note that the option text is added below the group
3. Use the arrow keys to change the radio selection
4. Not that the option text is not changing

**Comment by bkjohnson** [comment]
Possible solution: [switching `onClick` to `onFocus`](https://github.com/department-of-veterans-affairs/component-library/blob/8bebe09fed4166ea0f9f3687b097ca524192cbb8/packages/web-components/src/components/va-radio-option/va-radio-option.tsx#L66) since focus should be granted on clicking and keyboard navigation.

**Comment by jamigibbs** [comment]
@Mottie When using the `VaRadio` and `VaRadioOption` combination, the event that includes the radio option change details is the `onVaValueChange` event. And the radio option value is accessed at `event.detail.value`. That said, I've updated your [codesanbox example](https://codesandbox.io/s/hardcore-http-cox8li?file=/src/App.js:459-474) so that it uses that event with the expected event structure. Keyboard changes are working as expected.

The `onRadioOptionSelected` event is only used to communicate between radio options and the parent `va-radio` so it's not expected that that event would be used from `va-radio`.

I do think though that the documentation and examples for `va-radio` are not completely clear on what event to use so I'm going to see if we can update the [Storybook example](https://design.va.gov/storybook/?path=/docs/components-va-radio--default) to be more explicit.
