### ISSUE TITLE
[bug] `va-accordion` expand/collapse all button visibility

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/vets-design-system-documentation#1118]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

I found 2 minor issues with the `va-accordion` web component.
- If there is only one `va-accordion-item` within this wrapper, the "Expand all"/"Collapse all" button should be hidden, or update the documentation to describe the usage for only one `va-accordion-item`
- If all of the `va-accordion-item` elements inside the `va-accordion` are not rendered (or hidden), the "Expand all"/"Collapse all" button should also be hidden.

[Codesandbox demo showing the issues described above](https://codesandbox.io/s/competent-mclaren-20hpxr?file=/src/App.js)

## What I expected to happen

Hide the "Expand all"/"Collapse all" button when one, or less, `va-accordion-item` are visible within the wrapper

## Reproducing
- Formation version: Latest
- Device: (e.g. iPhone 8, Macbook): All
- Browser: (e.g. Firefox, IE 11): All

Steps to reproduce:

1. In the codesandbox demo, toggle the checkbox that shows and hides the `va-accordion-item`
2. Note that the "Expand all"/"Collapse all" button is always visible

**Comment by k80bowman** [comment]
In the [Slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1660933080161249?thread_ts=1660930161.119749&cid=CBU0KDSB1) on this support issue, @bkjohnson noted that he thought we had some guidance saying that an accordion should have two or more items, but it doesn't seem to be currently in our [guidance](https://design.va.gov/components/accordion).

@GnatalieH or @humancompanion-usds, do you have any thoughts on this?

**Comment by GnatalieH** [comment]
@k80bowman I also believe we should update our guidance to say that accordions should always have two or more items. If someone needs a single expandable content element, they can use Additional info. CC @humancompanion-usds

**Comment by Mottie** [comment]
https://staging.va.gov/decision-reviews/higher-level-review/#find-addresses-for-other-benef-8622

**Comment by bkjohnson** [comment]
Since that template is [setting `data-multiselectable` based on a CMS value](https://github.com/department-of-veterans-affairs/content-build/blob/9af577e75ab432e385cecc4a25620b2bc608751c/src/site/paragraphs/collapsible_panel.drupal.liquid#L28), a quick fix could be to add the `open-single` prop to the accordion if `entity.fieldCollapsiblePanelMulti` is false.

![A screenshot of Mottie's link above with the brower's inspector open. The markup representing the accordion is in view, and the `data-multiselectable` attribute on a wrapping container reads "false".](https://user-images.githubusercontent.com/2008881/186535594-2ff87564-2b0e-4d49-b9ad-090848fe42a2.png)
