### ISSUE TITLE
Foundation - grid page in Sketch core library is not accurate

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#1256]
## Details
In the Sketch core library, the [Foundation - grid page](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/p/3C1D41FC-679C-4A2F-8D77-881FB204A664/canvas) shows incorrect values for left/right margins. We should update this page to reflect the [left/right margin spacing units](https://design.va.gov/foundation/utilities/margins#margin-right-and-left) we use.

<img width="1161" alt="Screen Shot 2022-10-04 at 9 15 22 AM" src="https://user-images.githubusercontent.com/88347129/193843196-ea2f3c21-2242-4bf5-a6c7-b17530c82a3f.png">

## Tasks
Update the Sketch Foundation - grid page in the core library to use 8px for the Mobile left/right margins, and 16px for the Tablet left/right margins.

**Comment by caw310** [comment]
@LillyBoot @babsdenney , do we still need this ticket or can we close?

**Comment by LillyBoot** [comment]
It still looks to be incorrect in the sketch library, so we still need this ticket. It's a quick fix though. We could put it as a 1 and knock it out soon

**Comment by humancompanion-usds** [comment]
The problem here is that in production, sometimes it's 8px and sometimes it's 9.375px. It's inconsistent!!!! It is more often 9.375px so I will show that on the grids page, but that's not a spacing unit in our system either - it's wrong. This is due to the use of the `usa-width-two-thirds medium-8 columns` classes from v1:

![Screenshot 2023-10-11 at 4 40 53 PM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/52176351/20c2ae48-187c-476b-9703-5d5a0a5c66cf)

I do wonder if this will be different in v3, but the USWDS documentation seems gutter size agnostic.

**Comment by humancompanion-usds** [comment]
Fixed. https://www.sketch.com/s/bd089bc0-e3e3-4681-bf72-e6be22b433e4/p/C258CA59-FCB5-4B73-A4AA-723ACA440299/canvas#Version

Fixed the tablet gutter size which was wrong as well.
