### ISSUE TITLE
Reconcile a11y guidance on textarea use of placeholder text

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#1318]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

We have a [placeholder text option for textarea](https://design.va.gov/storybook/?path=/docs/components-va-textarea--default) and have advised users to use that for communicating max-character count in combination with text below the field. However, I don't see how that placeholder text is announced to screenreader users so that they would know there is a character limit (or whatever other information might be put into that placeholder text). 

Also, we annoyingly don't show this option in design.va.gov and thus have no actual guidance around it. Somehow all of this was missed when we got this component approved back in June.

## What I expected to happen

I expect the a11y guidance to describe how we make this placeholder text accessible. My understanding is that you can do that through screen-reader-only text in the label (at least, that's one method). 

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [x] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Details

This [came up in this thread](https://dsva.slack.com/archives/C01DBGX4P45/p1665683762425319) and is causing some confusion for the team implementing.

**Comment by SarahKay8** [comment]
Updated Guidance: 

Screen readers such as JAWS and NVDA don't read placeholder text, it's a visual addition only.
However, if you're providing important information visually (max character length) there is no reason you shouldn't be conveying this information to screen reader users as well. A good way to do this is with a screen reader only bit of text. Create a class using CSS which hides the text visually (off screen), and pop it into a span where you'd like it to be read out.

.sr-only {
  position: absolute;
  left: -99999px;
  height: 1px;
  width: 1px;
  overflow: hidden;
}
<label for=“Describe your situation>
  Describe your situation<span class="sr-only">No more than 16 characters</span>
</label>
<input type="text" placeholder="No more than 16 characters" id=“Describe your situation>


OR

Adding Instructions using Static Hint 

Instructions help users to submit the form successfully. However, if the instructions are provided with a placeholder attribute, then the user might not be able to use that instruction effectively. As placeholders disappear when the user starts filling in the form, users might miss critical information.

Example Syntax for Static Hint

<label for=”describe your situation”>Describe your situation</label>
<input type=”text” id=”describe your situation” placeholder=“No more than 16 characters” aria-describedby=”describe your situation-hint”>
<span id=”describe your situation-hint”>Max length should be no more than 16 characters long</span>



Could you review this? I can also add an option for `aria-placeholder`, but because that's not what our current component has I didn't. @humancompanion-usds
