### ISSUE TITLE
va-pagination onPageSelect event not being triggered

### ISSUE THREAD

**Issue by va-timorris** [department-of-veterans-affairs/vets-design-system-documentation#1323]
# Bug Report

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

I am attempting to use the va-pagination react component and the onPageSelect event is not being triggered when clicking on a page number.

Code:
const [page, setPage] = useState(1);
const handlePageSelect = (event) => {
    setPage(event.detail.page);
};

va-pagination
    onPageSelect={handlePageSelect}
    page={page}
    pages={10}

- I tried documentation here: https://design.va.gov/storybook/?path=/docs/components-va-pagination--default
- I also tried documentation here: https://design.va.gov/storybook/?path=/story/components-va-pagination--default&args=show-last-page:true
- That documentation seems pretty vague.  For example, instead of va-pagination, that documentation shows VaPagination.  Also documentation indicates that the event is named "pageSelect"  but example usage of the component in documentation uses "onPageSelect" - it would be helpful to include more code in documentation in storybook, rather than "onPageSelect={function noRefCheck(){}}"

## What I expected to happen

When clicking on a page number, the onPageSelect event should be triggered.

## Reproducing
- Formation version: 6.17.5
-  Component-Library version: 8.5.0
- Device: Windows
- Browser: Edge

Steps to reproduce:

1. Add va-pagination component to page
2. Give the va-pagination component a value for onPageSelect
3. Click on a page number in the component

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [x] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Attachments
[SearchPage.jsx.txt](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/files/9941485/SearchPage.jsx.txt)

**Comment by va-timorris** [comment]
[SearchPage.jsx.txt](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/files/9941480/SearchPage.jsx.txt)

**Comment by bkjohnson** [comment]
`pageSelect` is the event, and `onPageSelect` is the event handler. This is a [CustomEvent](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent), and at the moment React won't automatically register custom event handlers for custom events like it does for native events, such as `click`, `blur`, and `input`.

The reason that you see `<VaPagination>` in the storybook example is because we needed the React binding for the custom event handler. We have some [developer documentation on how and when to use these React bindings](https://design.va.gov/about/developers#react-applications).

This highlighted link will take you to the page just below the previous link:

![Screenshot of the pagination component on storybook, with the "how to use web component custom events" highlighted](https://user-images.githubusercontent.com/2008881/200073381-2bbe549e-e475-4185-be2a-7b85e9c07587.png)

![Screenshot of the developer documentation for the "React applications" and "Custom Events" sections](https://user-images.githubusercontent.com/2008881/200077413-e3162d0c-a3ca-4527-a05a-76a932ccffdc.png)

---

Do you have any suggestions on how we could improve the documentation? The `onPageSelect={function noRefCheck(){}}` that you see is something from Storybook that we [don't have much control over](https://github.com/storybookjs/storybook/issues/17701). However, in the "Story" addon on the "Canvas" tab you can see the code that was actually used in the example:

![Screenshot of the "Story" addon in the "Canvas" tab, with the tabs and code highlighted](https://user-images.githubusercontent.com/2008881/200077162-54e4f848-1c6f-4bf0-99d7-2da57164eeaf.png)

**Comment by va-timorris** [comment]
Thanks for the clarification.  I did see the Canvas sample of it working, but the "VaPagination" component will not work with us.  We always have to use the "va-pagination" component in our project.  Our app is not a purely React app, but a .NET Core web app using HTML Helpers to help render JSX react components (plus webpack as well).   The VaPagination working sample on the Canvas does not help us much since we need it to work with va-pagination.  I attached a text file with our JSX contents of the exact code that we have, which is not working.   I was hoping it was just a matter of me not using that va-pagination component properly.

**Comment by bkjohnson** [comment]
That's my bad on just assuming you were using React, apologies. I haven't worked in a .NET/React hybrid environment and I think this is the first time anyone has used our components that way. Does this mean that you can't import or use React components - you can only use it to render regular markup? I'm not quite understanding why `<VaPagination>` can't be used.

If all else fails, It should still be possible to use the component and event handler, but you may have to do it the old-fashioned way like:

```js

const element = document.querySelector('va-pagination');
element.addEventListener('pageSelect`, pageSelectHandler);
```

**Comment by va-timorris** [comment]
Hi - so two things:  so yeah, none of those variants of react components have ever worked for us, such as VaPagination.  The only thing that works when putting the VA design system components into our JSX files is the hyphenated variation of them, such as va-pagination.  Not sure why.  Fix it for us NOW!  Just kidding.   Second, I tried adding that event listener using react's useEffect hook and it works!  So for now I'll leave it at that.  Thanks.

**Comment by caw310** [comment]
We should document instructions in design.va.gov - in the for developers section about web components. Will add to DST backlog to add the instructions.

**Comment by caw310** [comment]
Turns out documentation is  already on design.va.gov (https://design.va.gov/about/developers#native-events) so closing.
