### ISSUE TITLE
USWDS - Step Indicator (Progress bar -segmented)  - Design

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1503]
## Description
We need to incorporate the designs for the USWDS Step Indicator (VA DS Progress bar -segmented) into the VA Sketch library. The version of this component with the different features from USWDS may need to live side-by-side with our component in the Sketch library for a time.

There may be some differences between the USWDS version and ours, so you'll want to do a small audit first to determine what those are. It would be helpful to present that audit to the team so everyone is aware. There may need to be some discussion about features we want to keep from USWDS and features we do not.

## Details
[USWDS Step Indicator component](https://designsystem.digital.gov/components/step-indicator/)
[VA DS Progress bar - segmented component](https://design.va.gov/components/form/progress-bar-segmented)

## Tasks
- [ ] Conduct small audit if necessary
- [ ]  Review DST backlog for outstanding design issues with this component, if necessary (if this component already exists and we are building a new version)
- [ ]  Create designs for component
- [ ]  Review designs with PO and/or DSC
- [ ]  Review designs with an accessibility specialist (if there is a11y support available)
- [ ]  Review designs with DST members (during a weds standup)
- [ ]  Address any comments from reviews, if necessary
- [ ]  Comment on this ticket with any accessibility considerations engineers may need to know
- [ ]  Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ]  Comment on this ticket with a link to the designs

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by caw310** [comment]
Will carry over into Sprint 24.

**Comment by GnatalieH** [comment]
Mockups:

- [Here is the link](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/v/58b3px/a/lR1J5yO) to the desktop artboard.
- [Here is the link](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/Gom72Gb) to the mobile artboard.

This one is tricky because the symbols need to be highly customizable to fit different numbers of steps, different states of completion, and different labels for the steps. I created 1-line and 2-line step label variations because the step counter at the bottom needs to maintain the correct margin of white space between it and the steps above it. I also created nested symbols for the steps that can be swapped from pending to current to completed, for example. And the symbols should maintain the correct proportions if the width is stretched. @humancompanion-usds ready for your review and feedback. Thanks.

**Comment by humancompanion-usds** [comment]
Agree that this one is tricky. How do I change the number of steps? I'm using the mobile symbol and I can control everything as expected except that I can't figure out how to add more steps. Still reviewing but wanted to figure that out before continuing. Thanks.

**Comment by GnatalieH** [comment]
We'll have to make different variations for different numbers of steps like the VA progress bar OR we can create individual symbols where Designers can piece together the number of steps they need @humancompanion-usds.

**Comment by GnatalieH** [comment]
@humancompanion-usds I made symbols under Step indicator / _elements so Designers can build out their steps as needed. There are symbols for the horizontal bars as well as large and small step number circles.
