### ISSUE TITLE
Add documentation for link behavior

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/vets-design-system-documentation#152]
# Feature Request

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [X] Content styleguide
- [ ] Component
- [X] Pattern
- [ ] Utility
- [ ] Other

## What is the name

1. Add documentation for link behavior to:

-  [Links section of the Content styleguide ](https://design.va.gov/content-style-guide/links)

- [Links section of Typography in Design documentation](https://design.va.gov/design/typography#links) 

## What is the nature of this update?

- [ ] When to use
- [ ] When to use something else
- [X] Code snippet
- [X] Accessibility
- [ ] Research insight
- [X] General documentation

## Additional Context

**For all links:**
- Links should only open in a new tab if clicking the link will result in the user losing progress or data.  Otherwise, links should open in the same window.
- This includes scenarios where a user may be:
  - immediately logged out of their [VA.gov](http://va.gov/) session, 
  - may lose their place in the middle of an application that is not saved, or 
  - may lose data that they are entering/uploading into a form.  
  - In all of these cases, it should also be considered whether the link is worth potentially taking the user away from where they are.

**For download links:**
-  semantically, the link is always a Hyperlink (`<a/>`), never a `<button>`.
- The media type and file size should be visually readable. 
- Use icons and color to enhance visual presence. 
- The download link should open in the same window.

## Code Snippet

For download links:
```
<!-- CSS from USWDS - need to recreate style for Foundation -->
<style>
[href^=http]:not([href*=".gov"]):after,
[target="_blank"]::after, 
[type="application/pdf"]::after,[target=popup]::after {
    background: url(https://designsystem.digital.gov/assets/img/external-link.svg) no-repeat 0 0;
    background-size: 100%;
    content: "";
    display: inline-block;
    height: .65em;
    margin-bottom: -1px;
    margin-left: .25rem;
    width: .65em;
}
</style>
<p>This is a 
         <a href="https://www.va.gov/playbook/downloads/Voices_Of_Veterans.pdf" download="WCAG_Checklist.pdf" title="Download the Voices of Veterans PDF" type="application/pdf">
                    download link  
          </a> <dfn>4.9MB, PDF</dfn>
 </p>
```

**Comment by jaredcunha-usds** [comment]
Just from what I'm seeing here, the code snippet looks like it's using the external link icon for anything not a .gov domain, as well as `_blank` targets and PDFs declared in a `type` attribute or popup control. This CSS snippet should not be copied as-is. 

But, the attribute selector would be the way to handle download links, and the documentation should indicate the attribute that sets the icon. I'd defer to the designers if that icon should go before or after the text. 

The CSS should go into Formation, and not `vets-website`.

**Comment by artsymartha68** [comment]
I have mocked up a "Download this file" for the Form Landing Page redesign project. I spoke with Ryan who is using the same already in the Pittsburgh site and I'm using his design (icon before the text):
https://www.va.gov/outreach-and-events/outreach-materials/

I think we need to add the Download icon to the icon page:
https://design.va.gov/design/icons

"Download" is one of those icons where folks tend to get creative and I'd like to see a standard established. 

https://fontawesome.com/icons/download
f019
<i class="fas fa-download"></i>

**Comment by jaredcunha-usds** [comment]
@artsymartha68 I'd love for someone to take a look at that icon page at some point. That was brought over from the old Fractal site (which no longer exists). The icons page is a limited set, but technically, the entirety of the Font Awesome free solid set is available. Same with brands.

**Comment by artsymartha68** [comment]
Sounds good @jaredcunha-usds 

I'll open a new ticket for that work and take ownership of it.

**Comment by jenstrickland** [comment]
@1copenut and I are reviewing the implementation of the icons with an accessibility lens, and have recommendations we're working on.

**Comment by KevinMHoffmanUSDS** [comment]
@jenstrickland Once you've got an update ready for the appropriate sections of design.va.gov, just @ message me and I'll make the changes. Cheers!

**Comment by jenstrickland** [comment]
Collaborating with @1copenut, we reviewed the icon implementations to ensure accessibility. 
- Added `aria-hidden="true"` to `<i>` to suppress the injected text content (that renders the icon) from screen readers
- To comply with WCAG, we edited link text to be clear about what the link does without the surrounding content. _(2.4.4, 2.4.9 - "**The link text MUST make sense in context, and should make sense when taken out of context** (problematic phrases include: “click here,” “learn more,” “more,” “read more,” etc.).)"_

**Download PDF Link Example**
```HTML
<a 
  href="https://www.va.gov/playbook/downloads/Voices_Of_Veterans.pdf" 
  download="Voices_Of_Veterans.pdf" 
  title="Download the Voices of Veterans PDF" 
  type="application/pdf">
    <i aria-hidden="true" class="fas fa-download vads-u-padding-right--1"></i>
      Download the Voices of Veterans <dfn><abbr title="Portable Document Format">PDF</abbr> (4.9<abbr title="Megabytes">MB</abbr>)</dfn>
</a>
```

**View Video Example**
```HTML
<a 
  title="Go to video about VA disability compensation" 
  class="video-link" 
  href="https://www.youtube.com/watch?time_continue=3&amp;v=xE0LzeRgdAk" 
  target="_blank" 
  rel="noopener ">
    <i aria-hidden="true" class="fas fa-play-circle vads-u-padding-right--1"></i>
      View video about VA disability compensation <dfn>on Youtube</dfn>
</a> 
```

**Download Graphic Link Example**
```HTML
<a 
  title="Download VA benefits to people who've served JPG" 
  class="file-download-with-icon" 
  href="/img/2019-07/VA-020-Web-Badges-205x175-al-1.02.jpg" 
  download="/img/2019-07/VA-020-Web-Badges-205x175-al-1.02.jpg">
    <i aria-hidden="true" class="fas fa-download vads-u-padding-right--1"></i>
      Download VA benefits to people who've served <dfn><abbr title="graphic">JPG</abbr> (0.11<abbr title="Megabytes">MB</abbr>)</dfn> 
</a>
```

**Download Word Document Example**
```HTML
<a 
  title="Download Learn how to apply for VA benefits Word document" 
  class="file-download-with-icon" 
  href="/files/2019-07/190111-ChooseVA-Marketing-Flyer-2019.docx" 
  download="/files/2019-07/190111-ChooseVA-Marketing-Flyer-2019.docx">
    <i aria-hidden="true" class="fas fa-download vads-u-padding-right--1"></i>
      Download Learn how to apply for VA benefits <dfn><abbr title="Word document">DOCX</abbr> (0.49<abbr title="Megabytes">MB</abbr>)</dfn>
</a>
```

**Comment by 1Copenut** [comment]
@CrystabelReiter This issue has relevance for the forms search, wanted to raise awareness to you and Emily for the findings and the open ask to update documentation.

**Comment by andaleliz** [comment]
@caw310, rather than open a duplicate, I just updated this ticket to include a request to add documentation for regular links as well as the download link Jen requested back in 2019.  The VSP process has changed since this was opened; I believe your team would be the one to make these updates now.  Please let me know if that's not the case. Thanks!

**Comment by GnatalieH** [comment]
I want to link this ticket to [this PR](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/GnatalieH-patch-2/src/_components/links.md) for documentation for Links as a Component.

**Comment by humancompanion-usds** [comment]
Feedback on draft:

1. I'm not sure I follow the logic here: https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/670#issuecomment-1072472247 However, I'd like to understand it and address it in the Links documentation, even if we don't have the Button component updated with an example. Because we start by saying "A link can trigger a download, such as a PDF" but that issue is saying that is not the case if we first generate the PDF. So perhaps we avoid PDF as an example in the opening text and then directly clarify when to use a link or a button for a PDF?
2. Are we going to show the link patterns in Storybook or just describe them or...? For example, "fa-download icon + 8px margin + Link text (PDF, page count)" which is then followed by a code snippet. I would prefer to show that alongside the description in a screenshot or to put it in Storybook (but perhaps Storybook is only for web-components?). To that end 2 more questions:
  * Is there a Sketch file where I can see these variations mocked up?
  * Should these in future be simple web-components whereby the title and page count could be passed in and we control the rest of the formatting?
3. To your question about icon following for PDF, I was talking about a secondary link variation of an Action link. I know Action links are currently in Experimental but, I see them all over va.gov. Can we graduate them at this point?
4. Is there an issue filed to address "Back to top" which, according to the presentation you linked to should really be a link and not a button? If not, let's file and fix that. 
5. PDF links should be an H2 like Video links. 
6. Per Martha's suggestion: "I think we need to add the Download icon to the icon page" - Let's do so.
7. The "[Download VA Form 21P-530 (PDF)](https://www.vba.va.gov/pubs/forms/VBA-21P-530-ARE.pdf)" example on https://design.va.gov/content-style-guide/links should be updated to match our PDF variation.
8. There are more Accessibility Considerations we can pull from that presentation you linked to. 
9. Links are in 3 places right now which...nein danke. We need to get down to just 2. Let's talk about how to reorganize.
  * Links (components): https://design.va.gov/components/links
  * Links (typography): https://design.va.gov/design/typography#links
  * Links (content): https://design.va.gov/content-style-guide/links

**Comment by caw310** [comment]
We will make action links part of links. Move action links out of experimental.

**Comment by GnatalieH** [comment]
> We will make action links part of links. Move action links out of experimental.

@caw310 after looking at the Action links documentation in Experimental, I believe we need an additional ticket to address moving Action links into the Links documentation I'm currently drafting. It's not going to be a matter of just copy + pasting content, I'll need to fold in Action links guidelines into the Links documentation in an intuitive, logical way. Would you like me to create that ticket, Carol? CC @humancompanion-usds.

**Comment by caw310** [comment]
@GnatalieH , yes please create any additional tickets needed.

**Comment by humancompanion-usds** [comment]
For item 1, I don't know that we need to show the button in Sketch.

I prefer Spanish v2 if we have to show the language. Am I understanding the use case correctly, that we'd have translated text that would link to a PDF in another language (i.e. a Spanish link that opens an English PDF)? If that's the case it makes sense to keep the language in the list of attributes of the PDF which is why I prefer v2. However, there are standards for abbreviating languages and countries that we should stick to: https://www.iso.org/iso-639-language-codes.html I think for Spanish it would be "es" (it's odd to me that it is lower case, but what do I know).

I do not like the "Link to video, YouTube call out" variation and think we could do without it. Much prefer no callout variation.

I'm working on item 9 from the list above now in a draft IA in Mural. Will share soon.

**Comment by humancompanion-usds** [comment]
Oh, also, the PDF download link secondary variation is great! We should show it alongside a primary Action link in the documentation to show how it would sit alongside that component.

**Comment by GnatalieH** [comment]
@humancompanion-usds I've been updating the [Links draft](https://design.va.gov/components/links) today. I'll also address some of your feedback:

1. I don't 100% follow the logic of this, either, but Allison requested we document a solution for this scenario. I don't think we need a button in Sketch, I just wanted to show you an example of how this button might look. I'll add a bullet point to the _When to consider something else_ guidelines that mentions using a button for the scenario where a PDF is generated and not just downloaded.
2. I've included screenshots of the PDF and video links in the updated Links draft. I used an example where YouTube is mentioned in the link text but not in parentheses. We may need to meet with Content on squaring away recommended link text for YouTube links, because I know @RLHecht has mentioned that YouTube links should be called out as such. FWIW, I'm also including a link to my [Sketch mockups here](https://www.sketch.com/s/efc66b9e-b823-4a1a-9e9b-86afb45d728b).
3. I will create an additional ticket to address moving Action links from Experimental and into this Links documentation.
4. I've been meaning to create a ticket for the Back to top issue, and will do so this week. I ran an Axe test on it in the past and want to include that info in my accessibility bug ticket. 
5. Fixed.
6. OK, I will create a ticket to add the download icon to the Icons page. Sounds good.
7. We'll need to talk to Content about syncing our documentation updates for Links. 
8. Do you have suggested additions? Want to discuss in our weekly meeting on Thursday? I'll review the presentation again in the meantime.
9. Thanks for working on this!

BTW, I don't know that we need to include a Spanish version example in our PDF link examples, I just had mocked it up. This is another issue we should sync with Content on. I copied the (esp) because that's how I saw it done for our 10-10EZ form. I don't know if Content has a preferred way of showing translated PDF link text. This might be something we can ask in one of their Slack channels.

**Comment by GnatalieH** [comment]
@caw310 I created [this ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/694) to address the Action links.

**Comment by GnatalieH** [comment]
@humancompanion-usds and @caw310 can we close this ticket? I have created a ticket to fold in Action links to the Links documentation as a follow-up. I can link to Matt's and my comments on this ticket from the new ticket. Since it's the last day of the sprint, I am hoping to close it. What do you think?
