### ISSUE TITLE
Forms Lib - Replace Modal Component

### ISSUE THREAD

**Issue by Andrew565** [department-of-veterans-affairs/vets-design-system-documentation#1534]
## Description

As part of [this epic](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/1530), we will replace all instances of the React Modal component in the Forms Library with the Web Component version.

## Details

The Modal component is currently being used in the following files:

- /vets-website/src/platform/forms/save-in-progress/ApplicationStatus.jsx
- /vets-website/src/platform/forms/save-in-progress/FormSignInModal.jsx
- /vets-website/src/platform/forms/save-in-progress/FormStartControls.jsx

## Tasks

- [ ] Replace the React component with its Web Component component, updating any necessary props and/or logic related to the smooth operation of the component
- [ ] Ensure the web component works correctly - likely, by either finding an existing app that makes use of it or by creating a new, temporary form
- [ ] Update any accompanying tests
- [ ] Get design sign-off to ensure that the new Web Component looks and feels 'correct'

**Comment by humancompanion-usds** [comment]
Is this one carrying over because of the issues found with testing in the Checkbox issue? Or is it something else?

**Comment by nickjg231** [comment]
@humancompanion-usds Yes, this issue is related to the shadow DOM issues encountered during unit testing of the Checkbox issue. However, the current issue is more complex than the Checkbox issue. In the Checkbox issue, testing did not require interaction with any elements within the shadow DOM, and I could assume other tests would cover whether it rendered correctly.

In the Modal case, however, the primary or secondary buttons in the modal are often tied to important functions defined in form components (such as `startOver`, `handleSignIn`, etc.). In such cases, the functions are only accessible by clicking the buttons in the modal, but the buttons render in the shadow DOM. Hence, it is no longer possible to assume everything renders correctly within the shadow DOM, and I must directly interact with these buttons. However, our testing framework does not render things within the shadow DOM, so currently, there are no buttons I can interact with, making it challenging to test. To address this issue, I am trying out a different testing framework and also have another, though not ideal, workaround that I can implement if necessary.

**Comment by caw310** [comment]
This ticket will carry over to sprint 25 due to illness causing delay on work for this.
