### ISSUE TITLE
Modal close button not rendering correctly on Modal Component page

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/vets-design-system-documentation#154]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

On the Modal component page, the Crisis Line modal example is missing the Font Awesome classes from the button, so it appears to be missing.

## What I expected to happen

Crisis line modal example should have a close button

## Reproducing
- Formation version: current
- Device: Macbook
- Browser: Chrome

Steps to reproduce:

1. navigate to https://design.va.gov/components/modal
2. Click on the `Get Help from Veteran Crisis Line` button

## Additional Info

Based on what I see in production, the design system documentation example needs to add the `.fas` and `.fa-times-circle` classes.

I also noticed the modal closes on keypress of the `Esc` key on va.gov, but not in the design system doc. Maybe that will be fixed once the correct classes are added? 

<img width="1201" alt="va gov-crisis-modal" src="https://user-images.githubusercontent.com/55992116/67960723-132d8e00-fbd1-11e9-9fd5-b0548a254cae.png">
<img width="1191" alt="design va gov-crisis-modal" src="https://user-images.githubusercontent.com/55992116/67960724-132d8e00-fbd1-11e9-9541-15ab58e0b4a8.png">

**Comment by KevinMHoffmanUSDS** [comment]
@andaleliz If you get a moment after Jenkins runs this afternoon, take a look and confirm this has been corrected. We may not have the necessary Font Awesome things in place to render this in design.va.gov, but I've made the quick fix to see if it's improved.

**Comment by jaredcunha-usds** [comment]
@KevinMHoffmanUSDS - This bug started appearing after we switched to a different version of Font Awesome. The Crisis Line button and modal are out of sync with the current site because much of the CSS is in `vets-website` instead of Formation, so that's something that will need to be addressed as well.

**Comment by KevinMHoffmanUSDS** [comment]
@jaredcunha-usds Thanks! Here's what I understand from your message: we need to update the CSS references to Font Awesome in Formation to match what is live in production. Is that the case?

**Comment by jaredcunha-usds** [comment]
At this point, I think it's this: There is some CSS that pertains to modals (regualar and crisis line) in here: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/sass/shame.scss and there's more crisis line CSS here: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/sass/modules/_m-crisis-line.scss — all of these would need to go into Formation to ensure the crisis line is consistent and can be placed on design.va.gov. 

It looks like the Font Awesome class names are updated on design.va.gov because I can see the close th buttons. But to get the visual presentation in sync, that CSS has to come over to Formation. Any CSS that is in `vets-website` can only be used on va.gov, and nowhere else. At some point, the only CSS that should be in `vets-website` should be for things that we don't want to make reusable on other parts of the platform.

**Comment by KevinMHoffmanUSDS** [comment]
@andaleliz @jaredcunha-usds I'm going to close this issue, because we've solved the immediate problem of the close button not displaying. As for the crisis line modals matching one-to-one, we'll be initiating a process for more regular "design system against production" QA efforts.
