### ISSUE TITLE
Improve hint text with aria-describedby

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/vets-design-system-documentation#1786]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

This consideration came from looking at the number input with hint text component and [this comment in a closed ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1334#issuecomment-1322553465) 

Currently the hint text for form components has no programmatic association to their form inputs so there is a high possibility that screen reader users are going to miss this text.

This was updated on the `<va-text-input>` component by adding a `message-aria-describedby` prop that would be available for screen reader users. It seems that, having 2 different messages (a visual hint and a sr-only hint) is an extra, unnecessary step that could leave room for human error. If the message is updated, it is definitely more likely that only the visual hint would be updated and QA'd and the SR message would be accidently forgotten.

Ideally if the visual hint text could be programmatically associated to the input on all form components using `aria-describedby` and `id` and there was not a separate SR hint that seems like it would be the better way to ensure accessibility.

## Urgency
How urgent is this request? Please select the appropriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [x] Other
We are building the new Income Limits app now and we are going to build this with the number input with hint text & number input with additional info components as they are. However, this is a very confusing app for a lot of folks. I am concerned that if folks do not have access to this hint text there might be difficulties completing it, especially on one particular screen. However, we are going to go forward regardless.

**Comment by jamigibbs** [comment]
>  It seems that, having 2 different messages (a visual hint and a sr-only hint) is an extra, unnecessary step

Hi @laflannery! Thanks for starting this discussion. The reason we needed to add separate sr-only text that maps to the `message-aria-describedby` prop is because `aria-describedby` in a web component with a shadow dom can not be made aware of an `id` element when it's _outside_ of the component. So we needed to bring the text within the component (inside the shadow dom) in order for it to make that connection.

The use case we are solving for started [from this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24502) where they needed to announce text that was not in the label, hint, or other visual component text (the design dictated that the text they needed to announce would be outside of the component). So adding this additional sr-only text with that `message-aria-describedby` prop was technically necessary in order to make that work.

Let me know though if maybe I didn't entirely explain our reasoning or understand the change you were hoping for here.

**Comment by laflannery** [comment]
Sorry @jamigibbs! Thank you for the explanation, this makes sense now. And my only remaining question was just when the other components would have an update for SR support so you just answered that. So yes, this can be closed now as far as I'm concerned. Thanks!
