### ISSUE TITLE
Alert box accessibility

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/vets-design-system-documentation#184]
# Support question

- [x] I’ve searched for any related issues/questions on github

## How can we help?

- Component/utility name: [Alert boxes](https://design.va.gov/components/alertboxes)

--> We used the alert box component on the Facility Locator search results page and [facility detail page](https://www.va.gov/find-locations/facility/vha_688GB) to indicate facility operating status. When used on the detail page, it raised a 508 compliance issue by skipping from H1 to H3. 

https://github.com/department-of-veterans-affairs/va.gov-team/issues/8299

![image](https://user-images.githubusercontent.com/55411834/80652829-07167200-8a36-11ea-9a85-77cfd639c944.png)

Is it possible to make the component flexible to implementation or 508 compliant?
-->

## What you have tried:

In the meanwhile, we will address this with HTML.

**Comment by humancompanion-usds** [comment]
Sure does seem like we have h3s in the web-component for Alert when we should probably have an h2, styled as an h3, because, to my knowledge, Alerts always appear after the H1 and before any other content. We actually don't have placement guidance on the Alert component page (we should) and we don't mention the header or needing to set it appropriately. Let's take a look at this. I'd hate to think that everyone is having to work around this.

**Comment by bkjohnson** [comment]
Closing since this is not an issue with the component. Any heading level can be used with `<va-alert>` by using the `headline` named slot.

Here is an [`<h4>` example](https://design.va.gov/storybook/?path=/docs/components-va-alert--heading-level):

![Storybook screenshot of the link above. The named `headline` slot is highlighted](https://user-images.githubusercontent.com/2008881/188999133-896643b9-4385-41ca-8245-45fd5344aa07.png)

And here's another example where an [`<h2>` is used](https://design.va.gov/storybook/?path=/docs/components-va-alert--default):

![image](https://user-images.githubusercontent.com/2008881/188999219-834db5d2-ede0-4f94-91c4-4980e3fce5df.png)
