### ISSUE TITLE
Update documentation to eliminate conflicting guidance for Process List & Additional Info components

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/vets-design-system-documentation#1888]
### Duplicate check

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### This update is for:

Component

### What is the name?

Additional info & Process List

### What is the nature of this update?

- [ ] How to build this component/pattern
- [ ] When to use this component/pattern
- [ ] When to use something else
- [X] Usability guidance
- [ ] Accessibility
- [ ] Implementation
- [ ] Research insights
- [ ] Package information
- [ ] Addition to Forms Library documentation
- [ ] Update to existing Forms Library documentation

### What problem does this solve?

Currently we have conflicting guidance between these the process list & additional info components in the Design System. In DS documentation for [process list](https://design.va.gov/components/process-list), we advise VFS teams **not** to combine this component with any others and say "content should be edited to fit the step, provide key information, and be visible by default." That would clearly mean no additional info components, which hide content. 

But then in the [additional info](https://design.va.gov/components/additional-info) guidance, there are direct instructions about using it within a process list. Which is correct?

**Comment by humancompanion-usds** [comment]
I'm going to pile on here and note an issue just brought to Office Hours: We give bad placement advice.

> Below a primary button to provide context about the action the button will take or to provide instructions in another language.

In fact, it should be above any buttons so that screenreader users would hear it before interaction with the button. This was added to allow for an [example](https://design.va.gov/components/additional-info#below-a-primary-call-to-action) that [now no longer exists](https://www.va.gov/health-care/how-to-apply/).
