### ISSUE TITLE
Secondary button should be styled with a white background, currently styled as transparent

### ISSUE THREAD

**Issue by artsymartha68** [department-of-veterans-affairs/vets-design-system-documentation#196]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

The covid screener is using the secondary button styling. However it appears as transparent yet we got input from the design system experts as well as accessibility experts that the background should be white. See attached issues. 

https://github.com/department-of-veterans-affairs/va.gov-team/issues/9610

https://github.com/department-of-veterans-affairs/vets-website/pull/13212

## What I expected to happen

Suggestion is to style it with a white background by default instead of transparent. That will ensure it looks correct regardless of background it sits upon.

**Comment by KevinMHoffmanUSDS** [comment]
Design System Council, 07/31/2020

For secondary buttons, the VA.gov Design System needs to provide usage and pairing rules. We don't want to make every ghost button white. 

Recommendation: Develop documentation, guidance, and reusable components for button patterns on the pattern page, including 
* OK | Cancel
* Previous | Next
* Buttons as Radio (e.g. COVID screener) 
* Button widths on mobile
* etc.

**Comment by artsymartha68** [comment]
cc @jonathanjnelson re: the Great Ghost Button Styling Discussion 😄

**Comment by caw310** [comment]
@k80bowman , let's prioritize this for an upcoming sprint.

**Comment by humancompanion-usds** [comment]
This is nearly done. Button guidance has been updated as of last week:
https://design.va.gov/components/button/

It now covers button width on mobile:
https://design.va.gov/components/button/#mobile-behavior

It does not show examples in production and does not cover the COVID screener usage of buttons as radios. That overlaps a bit with the Radio Button - Tile variation in USWDS but it's useful to document. Thus I'll keep this open to cover those remaining tasks.

There is also button pair:
https://design.va.gov/components/button/button-pair

That covers Progress (Continue/Back) which equates to Previous/Next. We'll be adding Confirm/Cancel which is already in Sketch. Button pair work is split into several issues but once the [final review issue](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/940) is closed it will be deployed soon after. 

* [ ] Add examples of button variations in production rather than having a bulleted list.
* [ ] Add COVID screener usage where buttons are used in place of radio buttons.
