### ISSUE TITLE
V3 Memorable date max length text wrapping issues

### ISSUE THREAD

**Issue by powellkerry** [department-of-veterans-affairs/vets-design-system-documentation#1965]
### Description

The memorable date component utilizes the va-text-input field with automatically shows the max length text when the limit is reached. The date and year fields are not very wide which causes the text to wrap to 3 lines. We need to come up with a solution to either display this text better or turn off the max-length text feature on the va-text-input

### Screen Shot 
![memorable-date.png](https://images.zenhubusercontent.com/620ff46ada91444aac696d7b/f3eb55df-5407-4d60-84bd-cf59ddbaab12)

```[tasklist]
### Tasks
- [ ] Work with design to come up with a solution to solve the wrapping issue, but still notify the user when they have reached the max character length
```

**Comment by jamigibbs** [comment]
I think the cleanest approach might be to just add a class to the components in va-memorable-date and then hide the hint text with CSS:

![Screenshot 2023-08-10 at 2 05 01 PM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/03804a49-a99a-4f02-989f-6ffe41d87734)

![Screenshot 2023-08-10 at 2 11 43 PM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/db195a36-f819-4413-8d99-03c50acb202c)

**Comment by jeana-adhoc** [comment]
When we brought our MVP form using memorable date through staging review, this issue was [flagged regarding the hint text.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63090). There might be some helpful guidance in the notes from @briandeconinck on how to approach this. Meanwhile, let me know if you have any questions or how I can help!
