### ISSUE TITLE
VA.gov Responsive Tables

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/vets-design-system-documentation#203]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.
There is a table currently in the Design System that looked close to what we needed:  
- We needed this to collapse down properly appropriately when displaying larger amounts of data on mobile screens.   
- We also needed our table to sort and have pagination specific for our needs so that might end up being separate.  
  - Sorting indicators at the column headers are coming soon, most likely arrows
- The styling we would like to move ahead with is with the **borderless table** and the **simple responsive list view** for the responsive table (per the VA Sketch Pattern Library)
- For awareness, there is this [VA.gov - Tables](https://design.va.gov/components/tables)

## Do you have a suggestion for a new component or utility?
Our suggestion would be to have a separate responsive table that reduces the data down into cards of some kind.  The current table seems best suited for smaller data sets.  We are matching what is in the Sketch file, less the online Design System.

## Additional context
There are some discussions about what the cards will eventually look like but those seem to be easy stylings.  At the time of this writing responsive labels are not meant to be in all caps.

### Proposed Component for View Payments
![EBN-tables_v3](https://user-images.githubusercontent.com/53826255/86408967-ff698880-bc85-11ea-99d8-82dd6c9845c3.jpg)

**Comment by CrystabelReiter** [comment]
Hi @jason-gcio ! 

The design system council met and discussed the responsive tables and we'd love to go through with adding this modified component to the design system. 

Here is some cumulative feedback and questions the group discussed last week. Please let me know how we can help this moving forward. 

We are aware that the simple responsive list table was adapted from the sketch library. Thank you (to Jim! @sporeboy ) for bringing that to our attention and we are going to make the same following changes. We also checked this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/10889 for reference on any changes. 

**Feedback format:** 
**Do:** Mandatory feedback
**Try:** Exploratory next step
**Consider:** Sharing ideas/alternate ways of thinking

### Simple Responsive List Table:
**Do:** 
- Outdent the text so its flush with the horizontal rule
- Revise the date heading for each row to be the same typeface, size, and weight as the labels provided, e.g. July 4, 2020 should be the same as “Amount:” (Source sans, bold, appropriate weight.
- Add a horizontal rule at the beginning of the table, after the “Displaying... “ heading before the 
   first “row.” 
- Make the “Payments returned” table consistent with the styling in the other table

**Questions:**
- There is no sort functionality on the mobile view. Is that intentional? 
- What is the recommended breakpoint, and how does it align with what we have in the system?
- What is your recommended CSS approach? Have you considered using “CSS grid?”

### Borderless Table: 
**Do:**
- Left align all table headings

Questions:
- Is sorting functionality necessary for all columns? Has your research with Veterans indicated that there are particular columns that are more important for sort? Let’s consider making it easier to do things that users are most likely to want to do, based on your research.  
- How do you know that the sorting arrows are clickable?
- How do you know which sorting arrow is the currently active sort? 
- How does sorting interact with pagination? If I resort, for example, does it stay on the current page or go to the first page? 
- What are the pagination recommendations - how many items in a table will begin pagination?

**Comment by jason-gcio** [comment]
@CrystabelReiter  - Thanks for looking at this!  We went through this and have some responses for you to consider. 

**Simple Responsive Table:**
> Do's   

All do-able  

**Questions - Answers**
> There is no sort functionality on the mobile view. Is that intentional?  

No, we do not have sort on mobile but we do have pagination and default sorting is by descending by date (newest first)

> What is the recommended breakpoint, and how does it align with what we have in the system?  

This mobile view starts at 768px, which is what we believe the tablet point in the Design System.  If there is another or better one we should use, please let us know.  

> What is your recommended CSS approach? Have you considered using “CSS grid?”   

We were worried that "CSS grid" would not be supportable in every browser, so we stuck with "display: table" for desktop and "display: block" for the mobile view using <td>, <tr>, and <th>'s.  We are using role or aria tags to help with screen readers.

**Borderless Tables:**
> Left align all table headings   

We thought it would be good to keep the numerical data (and subsequent headers) right aligned per a comment in a meeting, but we can move the headers to all be left - this will cause some disparity in those columns.  

**Questions:**
> Is sorting functionality necessary for all columns? Has your research with Veterans indicated that there are particular columns that are more important for sort? Let’s consider making it easier to do things that users are most likely to want to do, based on your research.  

We built this out to include all columns to cover different needs.  Anecdotally, some Veterans indicated they would use sort across all columns and others did not have an opinion.  This is something we will be looking at in our next usability sessions to get more clarification.

> How do you know that the sorting arrows are clickable?   

It was our understanding that the current arrows would indicate this, perhaps we could introduce a hover or outline effect.  The way it works now in the Design Library is that when you click a header, the arrow stays in place for descending/ascending.  This is all pretty hairy for screen readers and we are open to suggestion.  

> How do you know which sorting arrow is the currently active sort?   

The other headers do not show arrows, only the active column.
> How does sorting interact with pagination? If I resort, for example, does it stay on the current page or go to the first page?  

Currently it resets to the first page.  It is assumed that if you were sorting to see the first date and then not be taken to that, that's less than ideal.

> What are the pagination recommendations - how many items in a table will begin pagination?  

This is mostly dependent on how packed the data or how long the data in the rows are.  The convention is for there to be shorter lists and more pagination for mobile where real estate is at a premium.  This is completely adjustable if there is a recommendation here.  We intend to present 12 rows (potentially 1 year's worth of data) for desktop and 5 rows for mobile since that may look best given these data sets.

**Comment by CrystabelReiter** [comment]
@jason-gcio Thank you for taking the time to answer our questions! We really appreciate it 

I referred back to the group and regarding the borderless table and left alignment, it's fine for the header label to aligned left and the numerical content to be aligned right. 

Another thing to keep in mind about the date headers (if you haven't already planned on doing this), we can abbreviate the months in order to save room on the table: https://design.va.gov/content-style-guide/dates-and-numbers

I've talked to @1Copenut about the hairy screen reader situation with descending/ascending arrows. I'm going to copy and paste his response here: 

"...we’ve got a column showing a sort, and other columns that could be sorted on, and maybe some that can’t be sorted on. Three states:

- Sorted (active) column, and direction of sort

- Sortable column(s)

- Not sortable column(s)

I’d like to see the icon or icons hidden using SVGs and aria-hidden="true" and role="presentation" with SR-only text explaining the sort. So if we’re sorting on amount, the screen reader could announce “Amount, sorted low to high, column 2 of N”.

I’d like to see the sort direction indicated clearly using the arrow. These can be a bit confusing, so user testing is a big plus. I’m also interested in how the team will code these column headers. They will need to be links or buttons so they can take keyboard focus, and convey to screen readers that something will happen, and maintain the yellow focus halo."

Next steps here are once design and code is ready to go, please share those files with the design system council and we will direct those to VSP to fill out our backlogs to update the design system

**Comment by CrystabelReiter** [comment]
@jason-gcio Thank you for taking the time to answer our questions! We really appreciate it 

I referred back to the group and regarding the borderless table and left alignment, let's go with right aligned table headings on columns with numbers and left aligned for the others. 

Another thing to keep in mind about the date headers (if you haven't already planned on doing this), we can abbreviate the months in order to save room on the table: https://design.va.gov/content-style-guide/dates-and-numbers

I've talked to @1Copenut about the hairy screen reader situation with descending/ascending arrows. I'm going to copy and paste his response here: 

"...we’ve got a column showing a sort, and other columns that could be sorted on, and maybe some that can’t be sorted on. Three states:

- Sorted (active) column, and direction of sort

- Sortable column(s)

- Not sortable column(s)

I’d like to see the icon or icons hidden using SVGs and aria-hidden="true" and role="presentation" with SR-only text explaining the sort. So if we’re sorting on amount, the screen reader could announce 'Amount, sorted low to high, column 2 of N'

I’d like to see the sort direction indicated clearly using the arrow. These can be a bit confusing, so user testing is a big plus. I’m also interested in how the team will code these column headers. They will need to be links or buttons so they can take keyboard focus, and convey to screen readers that something will happen, and maintain the yellow focus halo."

Next steps here are once design and code is ready to go, please share those files with the design system council and we will direct those to VSP to fill out our backlogs to update the design system. Thank you again!

**Comment by KevinMHoffmanUSDS** [comment]
From the design system council discussion on responsive tables, dated July 17, 2020

* In the long term we need to develop more than one pattern besides a card-based pattern (for the mobile view) 
* If there are variant responsive actions, we'll want to catalog those by user goals
* We want to make sure that we don't "shoehorn" people into a single responsive table solution, responsive tables should reflect the user's information hierarchy needs first, and (complex) functionality (e.g. sorting, etc.) second

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/sass/modules/_m-responsive-table.scss now exists, this contains the css class `responsive` to be used on table elements. 

This is the minimum css needed to change

![image](https://user-images.githubusercontent.com/1094999/93799408-21333580-fc0d-11ea-8562-ad12f4dc0f02.png)

to become below on screen widths under 600px

![image](https://user-images.githubusercontent.com/1094999/93799442-298b7080-fc0d-11ea-9f55-93898ae7b081.png)

From "School Locations" accordion at https://staging.va.gov/gi-bill-comparison-tool/profile/11802405

**Comment by zurbergram** [comment]
The [GI ResponsiveTable](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/gi/components/ResponsiveTable.jsx) has been approved to resolve https://github.com/department-of-veterans-affairs/va.gov-team/issues/11055

This component along with [`table.responsive` css class](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/sass/modules/_m-responsive-table.scss) should be a good starting point for making responsive tables.

Both the component and css class are based off of the work done in https://github.com/department-of-veterans-affairs/va.gov-team/issues/10889 and setup to be generic enough for easy use for other use

**Comment by 1Copenut** [comment]
@zurbergram and team have given us an excellent blueprint for a responsive table component. I've tested it with mobile and desktop screen readers, and the W3C HTML5 validator. All checks are green and the semantics are maintained when we go to a single column at mobile size.

**Comment by bkjohnson** [comment]
The design system council decided to go with the responsive table from the `disability-benefits` app, and it is now part of `formation-react`:

https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/492
