### ISSUE TITLE
Broken V3 memorable-date link in the DST

### ISSUE THREAD

**Issue by jeana-adhoc** [department-of-veterans-affairs/vets-design-system-documentation#2149]
# Bug Report

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

In [design.va.gov the v3 Memorable date](https://design.va.gov/components/form/memorable-date#examples---v3) link to [storybook](https://design.va.gov/storybook/?path=/docs/uswds-va-memorable-date--default) seems to be broken

## What I expected to happen

Be able to navigate from the design system to storybook

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [Xs] This bug is not blocking any work
- [ ] Other

**Comment by humancompanion-usds** [comment]
This was momentarily broken as we deploy the component-library, which is what Storybook shows, and the documentation site, which is a separate Jekyll site. This sometimes happens when we rename or move a variation, which is what happened here: The month select variation became the default. But the link works for me now.
