### ISSUE TITLE
Figma rebuild: Templates

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#2196]
## Status
_Update each sprint until completed_
| Date | Status | Launch Date (see above) | Notes |
| ----- | ------ | ------------------------- | ------ |
| 17 Oct | in-progress | on-track | there are two more pattern updates needed |

## Description
There were many templates created in Sketch that will need to be included in Figma. This has a few different things to consider that would be good to get Designer feedback on. 

- What templates to include in Figma?
- What breakpoints are needed?
- Should these templates be in the Figma library or somewhere else?

- [ ] Templates page

## Details

- [Templates in sketch](https://www.sketch.com/s/c8df169f-5b02-4999-befb-34c7b3b62ba9)

## Tasks
Figure out 
- [ ] What templates that we will need in Figma
- [ ]  Breakpoints for templates
- [ ]  Where will the templates live
- [ ] Create templates and add to Figma

## Acceptance Criteria
 The design is the same as what is in the Component Symbol Library in Sketch. If 

- [ ]  Reviewed by other DS designer
- [ ]  Possibly review with VFS Designers
- [ ]  Review by PO

**Comment by caw310** [comment]
Adding to sprint 44 as unplanned work.

**Comment by humancompanion-usds** [comment]
Okay, much to cover here. Ideally, every pattern should have a corresponding template. That said, most of the patterns fall under forms and the Forms team has been revising those patterns. Thus their template is more up-to-date and what we'll bring into the umbrella of the Design System (and they'll continue to maintain it as they use it). 

* Accessibility templates. @jeana-adhoc and the a11y CoP are working on reviewing the CVS Health Figma library. We'll likely bless that as a library to use, perhaps reducing it a bit. We don't need to move these over.
* Benefit application templates. We need to bring these in. However, "Apply now" is the same as the Forms > Introduction template which it sounds like @rachelshearerux already converted.
* Blank templates. I believe we did these already?
* Email template. Very low priority. I'm not sure if the Notify team used these and they are the only team I'm aware of sending emails. We could reach out to them to see and then potentially archive these.
* How to apply (landing) page. Bring these into Figma but we need to figure out what lives where because this template is currently listed under Forms in design.va.gov but doesn't live in the Forms template file. Probably should? Curious to here thoughts from @rachelshearerux and @jeana-adhoc 


### Form pattern templates

For these, we have historically only had a smattering of the form patterns as templates. I'd like to fix that and have all of them covered. However, what we have may be out of date (teams have been iterating on some of these at different times) or incomplete. What Rachel and Jeana have done is definitely more up-to-date for the form step patterns they listed:
* Name and date of birth
* Identification information
* Relationship to the Veteran
* Mailing address
* Contact information (phone + email)
* Review page

Jeana is also working with Ryan on defining the One thing per page pattern for different form field inputs. Let's all of us designers convene with @caw310 and @tbaker1026 on this and make a plan for how to handle the form pattern templates. I suspect the answer is we use what Rachel has built and the DST takes on adding a template per-pattern. But I want to hear from you all and make a plan in unison.

**Comment by humancompanion-usds** [comment]
@danbrady and @LWWright7 - If you could list out the templates remaining to be done here that would be great, or if there are issues tracking the remaining work just point to them here. Thanks.

**Comment by humancompanion-usds** [comment]
* #3052 
* #3052 
* #3053 
* #3054 
* #3055 
* #3056

**Comment by caw310** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2196?planning-poker) with Zenhub @babsdenney

**Comment by LWWright7** [comment]
@caw310 this is the epic.  You want us to add an estimate for the epic?? Sorry...I'm confused...

**Comment by caw310** [comment]
@LWWright7 No need to add estimates to an epic. I removed the estimate request.
