### ISSUE TITLE
Change Military Address component to use radio buttons

### ISSUE THREAD

**Issue by t-michaud** [department-of-veterans-affairs/vets-design-system-documentation#2482]
### Duplicate check

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### This update is for:

Component

### What is the name?

Military address components

### What is the nature of this update?

- [ ] How to build this component/pattern
- [ ] When to use this component/pattern
- [ ] When to use something else
- [X] Usability guidance
- [X] Accessibility
- [ ] Implementation
- [ ] Research insights
- [ ] Package information
- [ ] Addition to Forms Library documentation
- [ ] Update to existing Forms Library documentation

### What problem does this solve?

**Current component design**
Currently, the design pattern [shown in the mock form for mailing address](https://staging.va.gov/mock-form-patterns/mailing-address) for the military address post office (APO/FPO/DPO) and State (Armed Forces America (AA), Armed Forces Europe (AE), and Armed Forces Pacific (AP) uses the select component. 

![mock-form-design-military-address](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/135402634/eee8f3a8-78d3-458d-9dd8-b6dc8c78a54f)

However, the design system recommends radio buttons for items with fewer than seven options.

**Suggested change in UI component to radio buttons**
- Change the select menu to the radio button component to be in line with the design system guidance. 
   - Radio buttons have a lower cognitive load because they make all options permanently visible so that users can easily compare them. 
   - Radio buttons can also be easier to operate for users who have difficulty making precise mouse movements.
- Additionally, consider changing the "APO/FPO/DPO" label to "Post office".
   - Using plain language rather than acronyms could help reduce confusion.

![guidance-example](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/135402634/7cdaac73-ec34-4195-a2f0-67c39000bcea)

### Additional Context

- Related [Slack thread](https://dsva.slack.com/archives/C01DBGX4P45/p1707234354787589) (internal)
- Related Ticket #2480 - Request to add military address pattern to Figma templates

**Comment by LWWright7** [comment]
@danbrady @babsdenney So....I didn't really know anything about this ticket until just adding it and am now digging into it...

But I don't think this is a component issue, but rather just a design change in the Form used to display the info/data, is that correct??

**Comment by danbrady** [comment]
@LWWright7 Right, it's an address pattern issue. Based on the guidance Thomas references above, we should use radios when there are fewer than 7 options. So those dropdowns he highlighted needs to be updated.

**Comment by LWWright7** [comment]
@danbrady @babsdenney this one is ready for [review](https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=2987-36363&t=Vq5WDS3wCQj1gmz6-1)!

**Comment by babsdenney** [comment]
@LWWright7 This LGTM! Thank you!

**Comment by LWWright7** [comment]
Thanks @babsdenney & @babsdenney..... just waiting to hear back from Laura & @megzehn from CAIA on Slack (that Matthew suggested):

![Screen Shot 2024-06-13 at 3 43 44 PM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/146852077/46feca73-63b0-4202-99ce-6a38fdd18902)

**Comment by LWWright7** [comment]
Design & verbiage approved per @megzehn <img width="509" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3htQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ee3e96089190f14756a6f29c26639c3e322bfa9c/Screen%20Shot%202024-06-14%20at%2010.35.41%20AM.png" alt="Screen Shot 2024-06-14 at 10.35.41 AM.png" />

**Comment by megzehn** [comment]
I'm belatedly chiming in here to add more context for the Military address component: 

- I initially suggested via Slack this label and response in place of `State`:

**Overseas “state” abbreviation**

- Armed Forces Americas (AA) - North and South America (excluding Canada)
- Armed Forces Europe (AE) - Africa, Canada, Europe, Middle East
- Armed Forces Pacific (AP) - Pacific

@DanielleThierryUSDSVA, @laurwill and I discussed and felt like "State" alone was confusing, since these aren't states. We landed on "Overseas 'state' abbreviation" based on [this USPS explanation](https://pe.usps.com/text/pub28/28c2_010.htm). And we expanded the responses so that it's clearer that Canada is included in the AE code. 

I realize this is more text than the existing pattern, so if there are concerns about length or any of these changes, we're happy to revisit and discuss. Thank you, all!

**Comment by caw310** [comment]
@megzehn can you provide some clarification? 
Are you proposing a modification to the guidance, Figma or pattern or all of them? Since this issue was closed in June, would you open a new issue with details on what you are requesting? That way we can put this in a sprint when we have bandwidth to address this.
