### ISSUE TITLE
Formation Deprecation - Typography Migration - Swap vets-website imports

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2538]
## Description
With the completion of [#2537](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2537), we're ready to attempt a swap of the css imports in vets-website from Formation to CSS Library **for typography**. 

## Considerations
- We currently have a mirror structure of necessary formation in css-library, so the hope is that the imports listed below can just be a path update.
- [vets-website module imports](https://github.com/department-of-veterans-affairs/vets-website/blob/20cfa222cbd98867014f5f4cc39433b59a06f3fa/src/platform/site-wide/sass/style.scss#L4-L26)
- [vets-website minimal.scss](https://github.com/department-of-veterans-affairs/vets-website/blob/d7663c0922a0fc850ec2f8370e1f66da2107385c/src/platform/site-wide/sass/minimal.scss#L1). This imports many of the same things that [style.scss](https://github.com/department-of-veterans-affairs/vets-website/blob/20cfa222cbd98867014f5f4cc39433b59a06f3fa/src/platform/site-wide/sass/style.scss#L5) does, the difference being that minimal imports things individually instead of through Formation's core stylesheet. 
- [prior vets-website PR](https://github.com/department-of-veterans-affairs/vets-website/pull/26606/files) that updates some typography values across the repo. 
- Similar to how we conducted significant QA on #2494 and #2525, we'll want to manually test our imports through verdaccio
- Not sure if this has to be an all or nothing effort. We may be able to get away with swapping 1-2 imports first as a test run before doing the rest. Or we may be able to do something like a phased rollout where we give teams a lead time for each import replacement. 

## Tasks
- [ ] Submit a PR into vets-website that updates the CSS-Library dependency and changes the import paths in the above stylesheets from Formation to CSS Library

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2538?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by micahchiang** [comment]
Imports by applications will also need to be updated: 

<img width="855" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM21hQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0798c207968c900d221683d17ba796554c63385b/image.png" alt="image.png" />

But, we can decide if this should be done separately

**Comment by powellkerry** [comment]
@caw310, @micahchiang  This is taking longer than expected due to conflicting imports, missing variables and files in css-library, and replacing hundreds of imports in vets-website. Currently I have the majority of imports replaced with only 42 references/imports remaining, most of these are imports of files that were not copied from formation to css-library. Once those files are copied and the imports are updated I can mark the css-library PR as ready and try to get a release out. Once there is a css-library release the PR for vets-website is now over a hundred files long, and will require approvals from a lot of code-owners.
My suggestion is that we treat this like the font-size task and mark this task as complete upon the css-library release, and create a new ticket to release the changes in vets-website. Otherwise I don't see this ticket being completed by the end of the sprint.

**Comment by powellkerry** [comment]
CSS library work is complete as far as I can tell. The new ticket for vets-website work is here: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2911
