### ISSUE TITLE
Consider adding the Subway Map as a component to the Design System

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/vets-design-system-documentation#260]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.

- Component/utility name: Process List, aka the Subway Map ( https://design.va.gov/components/process-list )

## Related Issues
* https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/247

## Do you have a suggestion for a new component or utility?
We currently have a process list as an HTML pattern, but it's not formalized as a React component. This should be built out as a React component because I've seen it used in forms, and thing there will be opportunities for more use as a form orientation page and inside applications with progress steps that Veterans must take in a specific order, but across days or weeks.

**Comment by KevinMHoffmanUSDS** [comment]
Design System Council, 07/31/2020

Since this will be added to Drupal and other places, we approve adding this to the system, however we also need to align the color, stroke weight, markup (including accessibility issues), correct the circles, to make sure that this is consistent across all implementation, including 

* Drupal 
* REACT
* HTML/CSS

Numbers may not be consistent because of resizability, e.g. the numbers aren't a consistent width. Potentially setting a fixed width, and not setting the circle size relative to the font size, would improve this design.

**Comment by bkjohnson** [comment]
@k80bowman I think this can be closed since we have `<va-process-list>`
