### ISSUE TITLE
Allow <va-link> to be a white link instead of default blue

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/vets-design-system-documentation#2602]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened
On the VA.gov homepage, under `VA NEWS`, there is a "Read the full article" link in white. I tried converting this to the DST `<va-link>` component, but there is no way to change the link color to white for this dark background.

<img width="600" alt="Screenshot 2024-03-19 at 11 39 45 AM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/19175324/6d847e83-74d2-451c-93ae-5760c307c808">

## What I expected to happen
To be able to make the link white

## Reproducing
Any/all browsers/platforms on va.gov

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [x] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

**Comment by randimays** [comment]
CC @FranECross @jilladams If we have links in our PW anywhere that need to be white, we're waiting on this ticket to complete before we can convert to `<va-link>`.

**Comment by jilladams** [comment]
FYSA @davidconlon : Homepage links white on blue cannot use DS web components until this ticket is resolved.

**Comment by humancompanion-usds** [comment]
@danbrady - This is fine to do in Figma to start. Can you define a token for a reverse link color and then hand-off to dev? Thanks.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2602?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by danbrady** [comment]
@caw310 Do we have a design issue for this? We haven't added this variation to Figma yet, and I'd hate to hold up Andrew. 

@Andrew565 I suspect the colors will follow what Link - Action (reverse) has, however we should really validate this in design (and on different backgrounds that are commonly used). Also, we haven't specified tokens for this. This would be a good candidate for "dark" mode token values... which we haven't quite sorted through yet.

**Comment by caw310** [comment]
@danbrady no there isn't a design ticket. I didn't think one was needed. I can write one up.

**Comment by humancompanion-usds** [comment]
We don't need an entire ticket and another sprint to figure this out. This link style is already out in production and seems to be a bug because the hover style is imperceptible. This is blocking sitewide from using va-link. Thus let's just do what va-action-link does on the home page as well and flip the color to yellow:

```
color: #face00;
background-color: transparent;
```

Dan - Please update Figma as well. Thanks!

**Comment by Andrew565** [comment]
Is the yellow color just for the hover and active states? I assume the 'default' link color will still be white?

**Comment by danbrady** [comment]
Yep, that's right. The text in hover and active states get that color. For your reference, here's the Action Link:

![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/381190/93e6512b-757f-4862-82a1-823e7e3c6d26)

This is one of those odd cases where Figma would take a bit more time to update than the code, IMO. With the current way we have the Figma Link component set up, it has 7 types x 5 states x 2 line versions (to account for inline wrapping), for a total of 70 variants. Here's what that looks like:

![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/381190/8efb56d9-0db3-4fe6-8597-66f52553eef3)



 Adding a new "reverse" property means an additional 70 variants. This isn't difficult but a bit time consuming, that's why I recommended a separate design ticket. We might be able to fit it in as a stretch item though, but it wouldn't be done in 15 mins safely. 😄

**Comment by Andrew565** [comment]
Screenshot of reverse link styles (active link is hovered-over to show that state):
![Screenshot 2024-05-01 at 2 13 33 PM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/147893/4e07908c-474b-4305-a57a-a7e646f2be8a)
