### ISSUE TITLE
Icon Button Component

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2641]
## Description
The [File Input designs in Figma](https://www.figma.com/file/UZys4hvw2Vwuo7U0pwbKbq/File-Input-v3?type=design&node-id=71-25203&mode=design) make use of Icon Buttons. These need to be added as either a variation on va-button, or a standalone component called `va-icon-button`.  Specific to file input are Change File, Delete, and Cancel, shown in the screenshots below.

<details><summary>Icon Buttons for file input</summary>

<img width="310" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWtoQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--701d45d22e4e6c2127614261bb15272d57589a82/image.png" alt="image.png" />

</details>

## Considerations
- Need to decide if this should be a variation of va-button, or its own component

## Tasks
- [x] Create either the va-button variation or the new va-icon-button component

## Acceptance Criteria
- [x] Above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2641?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by Andrew565** [comment]
Worth noting: 
- Right now the icons only appear to the left of the text, but that's not necessarily going to always be the case
- In the Figma designs, there are two different text/icon colors: blue for change file and red for cancel and delete
- Also in Figma, these 'buttons' are presented without borders around them to make them look like buttons, which is different from how primary and secondary buttons look today
- If we account for color, position, and icon name as separate props, that's three new props to add, plus a change to the border CSS property

Because of these considerations, I think there's value in making a new standalone component. Even though functionally it will act very similarly to va-button, there are enough changes to look and feel and API that I think a new component is warranted.

**Comment by Andrew565** [comment]
Decision was made to reuse the "va-button" event for analytics with the 'type' set to "tertiary" and the label reflecting the button's label. Decision also made to remove the 'disabled' prop option.
