### ISSUE TITLE
Cannot set width of va-select input

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/vets-design-system-documentation#2644]
# Bug Report

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

Can't set the width of a `va-select` component width without using custom CSS. 

Related ticket: #1712 

## What I expected to happen

Ideally, I would like to be able to have a `width` prop like is possible on the `va-text-input`.

## Reproducing
- Formation version:
- Device: Macbook Pro
- Browser: Chrome

Steps to reproduce:

1. Create a va-select or VaSelect
2. Try to change the width to a small size in the code

## Urgency
How urgent is this request? Please select the appropriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [X] This bug is affecting work currently in progress, but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Details

Here's what we've implemented in the FSR to accomplish this: https://github.com/department-of-veterans-affairs/vets-website/blob/4ed97e5e0438d2f45e66ba4c1f94568d36cdb738/src/applications/financial-status-report/components/employment/EmploymentRecord.jsx#L127

```     
<div className="input-size-5">
        <VaSelect
          name="type"
          data-test-id="employment-type"
          label="Type of work"
          required
          value={employment[index].type || []}
          onVaSelect={e => handleChange('type', e.detail.value)}
          error={showError() || null}
          uswds
        >
          <option value=""> </option>
          <option value="Full time">Full time</option>
          <option value="Part time">Part time</option>
          <option value="Seasonal">Seasonal</option>
          <option value="Temporary">Temporary</option>
        </VaSelect>
      </div>
```

https://github.com/department-of-veterans-affairs/vets-website/blob/4ed97e5e0438d2f45e66ba4c1f94568d36cdb738/src/applications/financial-status-report/sass/financial-status-report.scss#L268

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2644?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by jamigibbs** [comment]
Can the designers weigh in on this to make sure we want to add this functionality to `va-select`? This would be the same as [what we added here for `va-text-input`](https://design.va.gov/storybook/?path=/docs/uswds-va-text-input--widths). 

We added it to select because it's a [USWDS feature for text input](https://designsystem.digital.gov/components/text-input/) but I don't see the same thing for select:

![Screenshot 2024-04-02 at 9 36 26 AM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/010c7bb9-4c3d-47dd-9132-161477e86379)

cc @danbrady @LWWright7 @babsdenney

**Comment by LWWright7** [comment]
@jamigibbs - I don't see any issue with creating the same breakpoints for va-select that we use for va-text-input.  Of course, the dev would need to make sure that the right size selected would correspond to the length of the selectable items in the list so the text don't get cut off. I would like to hear more input from the design team.

**Comment by babsdenney** [comment]
@LWWright7 I agree with you. It doesn't seem like an issue, the main concern would be making sure the options in the select are not cut off. 

@jamigibbs It is strange that the width setting is noticeably missing from the select in the USWDS. Looking at this PR, the USWDS recently updated some of their components to include new values for variants. It looks like maybe the USWDS decided not to add the width value to the Select.  

[USWDS-Site: Fix component pages from audit (Phase 3)](https://github.com/uswds/uswds-site/pull/2291)

It might be worthwhile to ask the USWDS why they don't have a width variant for the select. The USWDS is [manually applying a width to the examples on the select page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-component-updates-phase-3/components/select/). I would like to know more of the reasoning behind why the USWDS doesn't have a select width setting.

**Comment by jamigibbs** [comment]
@josephrlee Can you provide a screenshot of the from that is using the `va-select` component where you'd need/want to adjust the width?

**Comment by danbrady** [comment]
I agree with what everyone has said and don't see an issue with adding sizes. Some other random thoughts:
* Since our components render browser-native `select` elements, I believe the browser/OS options popup should always be fully visible? (On mobile I think they popup in a scrollable area on the bottom of the screen?). Is this right? In other words, setting width only affects the select element, and not the popup after a user interacts with it. But this only applies to single select elements. Selects with `multiple` attribute could cut off the labels if the width is narrower.
* I don't know if there's a way in code to prevent a select from being narrower than its selected option. We'll likely still need to add something in guidance about having appropriate widths to prevent option labels getting cut off in it's "selected" state. For example, "Width of select should never be shorter than the longest label".
* The USWDS `select` uses `usa-input` as a dependency.  So you *could* use `.usa-input--[size]` (which sizes text inputs) on the `select` element to set it's width. They also don't have success/error states for their `select`. (Again, a user *could* use `.usa-input--success` or `.usa-input--error` for this, but I'm not sure if they *should*.) I'm curious if the USWDS simply hasn't considered adding these classes directly to their `select` or maybe just didn't document to use the `usa-input` ones. 🤔

**Comment by josephrlee** [comment]
@jamigibbs, here's one of the places on the FSR. There's a handful more scattered throughout the FSR:

<img width="960" alt="Screenshot 2024-04-02 at 4 17 08 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/1631062/598e60ae-9922-47a5-b9f2-7ac18b7cc902">

When our custom class is not applied, it inherits the full `max-width` of `480px` from the component: 
<img width="975" alt="Screenshot 2024-04-02 at 4 17 53 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/1631062/34b5e983-1c4b-40b5-a51c-ec29c7949cee">

**Comment by josephrlee** [comment]
Unrelated to this request, I think our form is probably using the wrong component altogether. There are only 4 options in this screenshot above, so it should probably be a radio button group instead. 

<img width="440" alt="Screenshot 2024-04-02 at 4 23 40 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/1631062/b3d1dcfa-5375-4553-9c60-c1f1c2552545">

**Comment by jamigibbs** [comment]
> Unrelated to this request, I think our form is probably using the wrong component altogether. There are only 4 options in this screenshot above, [so according to the USWDS guidance, it should be a radio button group instead](https://designsystem.digital.gov/components/select/).
> 
> <img alt="Screenshot 2024-04-02 at 4 23 40 PM" width="440" src="https://private-user-images.githubusercontent.com/1631062/318986103-b3d1dcfa-5375-4553-9c60-c1f1c2552545.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNjE3MTYsIm5iZiI6MTcxMjE2MTQxNiwicGF0aCI6Ii8xNjMxMDYyLzMxODk4NjEwMy1iM2QxZGNmYS01Mzc1LTQ1NTMtOWM2MC1jMWYxYzI1NTI1NDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDNUMTYyMzM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDg1ZjQ5NjM1YTQ3OWJkNWM5M2RmY2FiMjcyM2EzMDBmYzM5ODRjODNhM2E5MGQ0MDg4OTM4OTRhYWVmMmMxMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DdVGOfI7LnFVYcZ0Z0hcj3guc3Zyj2_hErvBXYvMwPU">

@josephrlee That's a good find. It does look like the design system would like it to be radio group with only 4 options. 

I think we can still add the width option to `va-select` but you might want to check in with your designer to see if you can just change your implementation to checkbox instead.

**Comment by josephrlee** [comment]
@jamigibbs , I am one of the designers on the team. :) I [created a ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/79856) on our teams board to get it done. Just need to check with our FE's on the level of effort for it! Also, thanks for getting the width prop added to the `va-select`!
