### ISSUE TITLE
Autofill in Safari with va-text-input component does not work properly

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/vets-design-system-documentation#2668]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

If I use autofill to fill a `<va-text-input>` field on Safari/iOS and Safari/Desktop, I am not able to submit the form as I get errors indicating that the fields are still blank.
[Video of this occurring](https://us02web.zoom.us/clips/share/0TgKimPTIHzLar8AYLC3rzziWYrHlSW2TFPtDrrnRRij3_stp71TBqoweNqgcXaK54MBRajPwxPL9HI-eZE7pwXE.mroy-wQ2Im4JFpH5)

## What I expected to happen

I would expect that if I use autofill to fill in a field, that the form would submit properly when I try.

## Reproducing
- Formation version:
- Device: iOS (Phone and iPad), Mac
- Browser:  Safari

Steps to reproduce:

1. Go to a form using the `<va-text-input>` component, for example the 
[Find a VA accredited representative or VSO](https://www.va.gov/get-help-from-accredited-representative/find-rep) or the [Request a Presidential Memorial Certificate](https://staging.va.gov/burials-memorials/memorial-items/presidential-memorial-certificates/request-certificate-form-40-0247/veteran-personal-information)
2. On iOS/Safari fill in the form, making sure to use autofill for any fields you can
  - Specifically the Address/Zip field on the Rep form and the First name and Last name on the Presidential Certificate form
3. Scroll down and submit the form
4. Notice that the specified fields have errors and the error message now shows asking you to enter information.

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [x] Other

### Details
- This bug, while it is not necessarily blocking work, it is an issue for any field using the component which is probably a lot of fields and a lot of forms, especially now are there is a larger push to make sure everything is using components as much as possible. 
- This bug does not happen on iOS/Chrome.
- This bug does not happen on forms that do not use components, [for example this one](https://www.va.gov/health-care/apply/application/id-form)
- One theory that might be happening here, if it helps, is that when the autofill is selected, that may not be being passed to the `value` in the component, and is actually only changing the visual display. Therefore when the user submits the form, the value is still technically empty.

**Comment by jfinnerty13** [comment]
Video of the bug (which happens on both phone and desktop): https://us02web.zoom.us/clips/share/0TgKimPTIHzLar8AYLC3rzziWYrHlSW2TFPtDrrnRRij3_stp71TBqoweNqgcXaK54MBRajPwxPL9HI-eZE7pwXE.mroy-wQ2Im4JFpH5

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2668?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by it-harrison** [comment]
Hi @laflannery @jfinnerty13 I have not been able to reproduce this bug on Safari 17.5 for Desktop. I have watched the linked video but am a bit confused. When I visit the [find a rep page](https://www.va.gov/get-help-from-accredited-representative/find-rep), I don't get a prompt to use Autofill.  In Safari when I do get a prompt, I see  something like this: 

<img width="789" alt="Screenshot 2024-07-25 at 10 44 01 AM" src="https://github.com/user-attachments/assets/beeaa816-3500-4d1a-9c81-2a43b2248eb0">

But in the video there is no icon in the right of the field - it seems as though the zip code were pasted into the input? But when I try pasting and hitting return, the page works.

**Comment by jfinnerty13** [comment]
So I'm not 100% sure but it looks like the user did auto fill using their contact cards which you can do by entering Shift+Command+A or going to the 'Edit' > 'Autofill Form' in the top navigation. Maybe try that to see if it triggers?

**Comment by it-harrison** [comment]
> So I'm not 100% sure but it looks like the user did auto fill using their contact cards which you can do by entering Shift+Command+A or going to the 'Edit' > 'Autofill Form' in the top navigation. Maybe try that to see if it triggers?

@jfinnerty13 - thanks much, the "Shift + Command + A" worked!

**Comment by it-harrison** [comment]
**Overview**:

The heart of this bug is that on Safari, when a user encounters an input field and uses the keyboard shortcut "Command + Shift + A" to fill that field, the field **is** filled but the browser will **not** fire an `input` event the way it does if, for instance, a user were to type a character in the input field.

The consequence of this behavior is that in application code like `<va-text-input onInput={myFunc} />` the call back `myFunc` does not get executed when the `va-text-input` element is autofilled. When `myFunc` does not get executed the component enters into a state the engineer did not intend: the form state does not match the state of the field, and errors inevitably result.

In the first example cited in this ticket, [Find a VA accredited representative or VSO](https://www.va.gov/get-help-from-accredited-representative/find-rep),  there is a `va-text-input` element in a `form` with a callback passed to `onInput`:
<img width="641" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFFqQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--af4f52ed7a12d3520711c4e431d704f420b932a1/Screenshot%202024-07-31%20at%203.44.13%20PM.png" alt="Screenshot 2024-07-31 at 3.44.13 PM.png" />

When the user autofills this field, the `handleLocationChange` function is not executed. Then, when the user hits the 'enter' key the form is submitted; during the process of submission an error state is entered because the `handleLocationChange` function was not called.

The other example in this ticket involves a form that uses the forms-system for rendering and validation; here the same problem happens -- so far as the code can tell, the field is empty and therefore when the form is submitted it enters an error state as if the fields really were empty.

Solutions:

I investigated if there is a way to detect from inside the `va-text-input` component that its `input` has been filled by an `autofill` and, if so, to emit an `input` event, but there does not appear to be any mechanism to detect that an autofill has occurred.   

This means that either: 

* VFS teams need to check for fields having been filled by autofill. For example, in the Find a VA accredited representative or VSO example, the coponent can check when a user hits enter if a field has been filled, and if so, process that input, thereby avoiding an error state. I am not sure how this would work in the forms-system; it may require intervention from the forms team.
* It may be possible to add a dependency or write a utility that checks form fields that are filled and compares that to internal state; if the state is empty then it will be updated to match the field's value. This would not be a trivial exercise since the code would need to run on every page with a form, and would need to work with stand alone forms and with forms-system forms.

If possible we should try to go with the first option - this will require notifying teams of the need to incorporate an autofill check into their forms.

**Comment by caw310** [comment]
@laflannery please see Ian's overview. This isn't something DST can fix.

**Comment by laflannery** [comment]
@caw310 I understand this (as much as possible at least) However, I feel like this should be updated in the documentation somewhere. So that teams and engineers going forward know that this is something they need to do. Would that be possible?

**Comment by caw310** [comment]
@laflannery Ian will add documentation in Storybook.

**Comment by it-harrison** [comment]
Pr is here: https://github.com/department-of-veterans-affairs/component-library/pull/1256

**Comment by jfinnerty13** [comment]
@laflannery @caw310 is there anything I should tell my team about this as next steps? Thanks!

**Comment by laflannery** [comment]
@jfinnerty13 I would direct them to this ticket and Ian's comment above to how they should code for the autofill. This has also already been [added to the documentation](https://design.va.gov/storybook/?path=/docs/uswds-va-text-input--docs#autocomplete) so directing your engineers here would probably help as well
