### ISSUE TITLE
Heading typography is different on design.va.gov from the production site

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/vets-design-system-documentation#267]
# Feature Request
@jenstrickland brought up a great point in a Slack thread yesterday about the difference in heading typography between design.va.gov and production:

> There's a difference in heading styling as noted in the VA design system and Formation CSS.
>  * In the design system, H2, H3, H4, and H6 are Source Sans Pro. H1 and H5 are Bitter.
>  * In Formation, all headings are Bitter.
> 
> In general, serif fonts may be more difficult for readers to comprehend, especially for long, bold text strings. If the design system council has an opportunity to revisit the history of the difference in the VA design system documentation and the Formation CSS, that would be helpful. The sans-serifs will be easier, quicker to read for the most people. I started to document in an issue ticket, but then wasn't sure which issue template was the correct one to use.

---
![Screen Shot 2020-07-14 at 10 32 13 AM](https://user-images.githubusercontent.com/934879/87829753-425e5b00-c845-11ea-8a36-bf5f71495b43.png)

---
![87439104-5e040000-c5be-11ea-8bc1-eacd77d03ce2](https://user-images.githubusercontent.com/934879/87829763-47bba580-c845-11ea-8355-314b2a6a163d.png)

- [ ] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [ ] Content styleguide
- [ ] Component
- [ ] Pattern
- [ ] Utility
- [ ] Other

## What is the name

This is a two-part issue. The first thing to do short-term is to update design.va.gov to match what our headings are doing in production.

The longer-term thing would be for the design system council to explore considering Source Sans Pro for headings. Some questions include whether this is all headings, all headings expect H1s, and what level of effort this might require. This would likely depend on a robust visual regression test suite; changing CSS always has some level of risk for visual breaks.

## What is the nature of this update?

Documentation and potentially production CSS

- [ ] How to build this component/pattern
- [ ] When to use this component/pattern 
- [x] When to use something else
- [x] Usability guidance
- [ ] Accessibility
- [x] Implementation
- [ ] Research insights
- [ ] Package information

**Comment by 1Copenut** [comment]
Pinging @KevinMHoffmanUSDS && @rtwell && @CrystabelReiter for awareness.

**Comment by jenstrickland** [comment]
Another avenue to consider is the possibility of moving away from web fonts. There's a trend among performance-minded sites to go back to system fonts. I read something on this recently, and can't find it just now. If I do find it later, I'll add a comment.

Some things to consider about web fonts: 

- They impact page load time. 
- They leave the site vulnerable to Google or any other font/cdn vendor going down.
- There is a [FOIT (flash of invisible text) of FOUT (flash of unstyled text)](https://css-tricks.com/fout-foit-foft/) which may introduce 508-defect-0 accessibility issues in the animation movement, if the web page load is particularly impacted or certain web dev techniques are used, such as font-display:swap, due to the visible "switch" of fonts on slow 3G connections. [Read more regarding the amount of movement as fonts load on a page](https://www.zachleat.com/web/font-display-reflow/).
- VA.gov is currently loading a number of font styles — particularly Font Awesome — that we could likely reduce to improve performance and minimize the animation.

There are techniques to consider to improve web fonts performance, and this article does a nice job of outlining them: https://www.keycdn.com/blog/web-font-performance
