### ISSUE TITLE
Bug - On This Page Icon Alignment

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2849]
## Description 
The icon alignment for `va-on-this-page` is slightly off compared to what's currently in production. Icons need to come down slightly so they're vertically centered with the text. 

Production on the left, staging on the right:
<img width="1093" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlgzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1f1f104f5f44b7313965d37eae88d69714e9a588/image.png" alt="image.png" />

## Tasks
- [ ] Update `va-on-this-page` so icons are vertically aligned properly

## Acceptance Criteria
- [ ] Tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2849?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by jamigibbs** [comment]
The icon alignment seems to be fixed now so I'm going to close this issue.

But I'm going to open a new one because there isn't an indent on the left side anymore like it shows in [Figma](https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=1064-42022&node-type=instance&t=VIFSJDRDiJHoXTi4-0).

**Storybook**

![Image](https://github.com/user-attachments/assets/5abb4346-f98e-4dd8-b29a-30574e2acdc4)

**Figma**

![Image](https://github.com/user-attachments/assets/512e43eb-39c1-4823-9497-7999c7c48c06)
