### ISSUE TITLE
va-textarea is not resizable

### ISSUE THREAD

**Issue by rhasselle-oddball** [department-of-veterans-affairs/vets-design-system-documentation#2977]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

va-textarea doesn't allow resizing. This feels necessary when you have 3000 lines of text to enter. Current textarea visible area is about 400 characters.

va-textarea doesn't allow resizing:
![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/123402053/796f0e2a-8631-45d2-8443-d5c0a751dfa5)

Old deprecated widget allows resizing:
![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/123402053/80dc1415-2298-4bb1-8a8c-ab4829dd851d)

## What I expected to happen

va-textarea should be UX friendly if I have a lot of text to enter

## Reproducing

- Formation version:
- Device: Windows 11
- Browser: Crome

Steps to reproduce:

1. check [va-textarea on storybook](https://design.va.gov/storybook/?path=/docs/uswds-va-textarea--docs)
2. notice it is not resizable
3. try UX for yourself. pretend you have to write a lot of text, 3000 lines long.
4. It's a bit hard with the small viewport.

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2977?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc

**Comment by jamigibbs** [comment]
I'm not sure when this regression happened but when the v3 variation was added, we [specifically added resizing style](https://github.com/department-of-veterans-affairs/component-library/pull/654#discussion_r1142707870) so that the resizing would work (the [USWDS version](https://designsystem.digital.gov/components/text-input/) does have it too):

```css
.usa-textarea {
  resize: inherit;
}

```

Removing [the override style from the component stylesheet](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/web-components/src/components/va-textarea/va-textarea.scss#L16-L18) should resolve it though.
