### ISSUE TITLE
Discovery: CSS is hoisted out of parent class in style-consolidated stylesheet

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2980]
## Description
We recently discovered unexpected behaviour where a stylesheet imported into [style-consolidated.scss](https://github.com/department-of-veterans-affairs/vets-website/blob/9ef0eaafd7a173b60785f22147c48208efff2e03/src/applications/proxy-rewrite/sass/style-consolidated.scss#L111) was getting hoisted out of its parent class at some point during compilation. This caused an unexpected visual regression in teamsites that added some margin to the top and bottom of paragraph elements. As of now, it isn't clear why this is happening and we'd like to learn why it is. 

## Considerations
- [Slack thread](https://dsva.slack.com/archives/C01DBGX4P45/p1719264669528139) that contains additional context around the phenomenon. 
- unsure if this is a webpack compiler setting, something specific to how the web components global stylesheet is constructed, or some other strange gotcha

## Tasks
- Attempt to reproduce the unexpected hoisting behaviour highlighted in the slack thread above. 
- Write up the findings in a doc and suggest a fix if possible

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2980?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by rmessina1010** [comment]
It appears that imported CSS was being hoisted because the import statement is not using the correct file type and format.

In order to import a stylesheet within a class as we were intending to, we must name the inner file with an underscore, and ending in scss. .Yes, even if it's plain css, i.e.   `@import '~@department-of-veterans-affairs/component-library/dist/main.css';`
 →   `@import '~@department-of-veterans-affairs/component-library/dist/main' ;` and of course, `main.css` renamed to `_main.scss`

Specific to this ticket:  `main.css` contains more  rules that were intended to be imported, as such the file may not need  to be  imported within the `.consolidated` class.

**Comment by humancompanion-usds** [comment]
@rmessina1010 - Is there an issue tracking our implementation of these changes or did we already make these changes?

**Comment by micahchiang** [comment]
@humancompanion-usds - we don't have an issue yet for implementing changes, and actually with Randi's recent work to completely decouple the injected header, we likely won't need to do anything on our end to guard against this happening again. Her rework of the [style-consolidated.scss](https://github.com/department-of-veterans-affairs/vets-website/pull/27590/files#diff-e4e1e7779d08bb98c49c553082c993ea1800cbb11850640934a3ffd3fb37d473L111) file completely removed the import of  `component-library/dist/main.css`.
