### ISSUE TITLE
Anchors inside va-introtext don't inherit font-sizing, so anchors are too small

### ISSUE THREAD

**Issue by dcloud** [department-of-veterans-affairs/vets-design-system-documentation#2981]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

The "Go back to the previous version of My HealtheVet" link is inside of a div with the `.va-introtext` class applied. The USWDS typography changes introduced in https://github.com/department-of-veterans-affairs/vets-website/pull/30089 appear to override the intended font-size of text in the `va-introtext` component

![Screen Shot 2024-06-28 at 13 09 22](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/279327/58f71ffb-ddc3-4af0-ac5c-efb7f66cac21)

## What I expected to happen

Text for an anchor element inside of the `.va-introtext` element to inherit the intro text font size

## Reproducing

- Formation version:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)

Steps to reproduce:

1. Load a page with an anchor element inside an element with the .va-introtext applied.

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

**Comment by micahchiang** [comment]
## Proposed Fix
anchor tags in `.va-introtext` elements need a little more specificity to ensure they inherit the right font-size. In order to keep formation and css-library in sync during our transition, this needs to be updated in two places: 
1. Add `a` to [this style block in Formation](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/05cbc7285123c70f79094b13264321915214d6d3/packages/formation/sass/base/_va.scss#L420-L425) so it reads `p, a {...}`
2. Do the same as above to [this style block in css-library](https://github.com/department-of-veterans-affairs/component-library/blob/e1a112190aa8ddabaed8a20a8b45a7f2e586f6aa/packages/css-library/src/stylesheets/base/va.scss#L350)

Once these changes are made, new releases for both Formation and css-library should be created and published to vets-website.

**Comment by micahchiang** [comment]
formation PR - https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/1046

**Comment by micahchiang** [comment]
Closing. Resolved here - https://github.com/department-of-veterans-affairs/vets-website/pull/30604
