### ISSUE TITLE
Increase distance between stacked accordions to create a more accessible click/tap target zone

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/vets-design-system-documentation#314]
# Feature Request

## Is this feature request relating to an existing component or utility? Please describe.
[Accordion](https://design.va.gov/components/accordions)

## Additional context
When we have stacked accordions on VA.gov, they're currently only 5px apart.  That's not a sufficient distance between clickable elements to prevent people from clicking the wrong thing.

If we increase the space between accordion elements (actually all clickable elements, but I notice this on accordions), we can help prevent user error.

There isn't a specific recommendation in WCAG for distance between tap targets, and I haven't been able to find recommendations on this from reliable sources online.  @jenstrickland shared that Apple Interaction Design Best Practices used to recommend 22px spacing between touch targets, to help those with mobility considerations.  That seems reasonable to me, and based on my quick-n-dirty assessment, also aligns with the distance between tap targets on GOV.uk (on mobile).

Peeking at our code, I _think_ we'd have to add some kind of class to the `<ul>` that contains the accordion stack, and it's not a matter of simply increasing the margin on the accordion `<button>` trigger itself.  

## Acceptance Criteria
- [ ] Create and/or modify unit tests for this component to include an aXe scan

**Comment by 1Copenut** [comment]
I agree with both sentiments to increase spacing between accordions and increase the hit space for each by bumping up the padding. This will make each accordion easier to toggle when folks are using a tap gesture on phones, and should help prevent accidental toggles with the extra space between elements.

**Comment by GnatalieH** [comment]
@1Copenut I'm reiterating what you said, essentially. I suggest we follow the margin settings between headers that USWDS uses for [their accordion component](https://designsystem.digital.gov/components/accordion/), no more space than that, and increase the header target space to equal the 22px we're aiming for. I'm wondering, also, if we have evidence/research that users are actually tapping the wrong accordion element and having an issue with this component. I know the issue came up during testing. But increasing the margin between elements too much will break the law of proximity (gestalt principle).

@cvalarida and @bkjohnson, can we add another header in our accordion example in Storybook (so there are three headers, at minimum)? I think it will make it easier to understand a real-world example of how this component can be used. Thanks.

**Comment by bkjohnson** [comment]
Yeah, we can definitely add another accordion item.

**Comment by andaleliz** [comment]
Hey, just catching up on all the great convo that has recently taken place here.  Thanks for taking a look at this/

>if we have evidence/research that users are actually tapping the wrong accordion element and having an issue with this component. I know the issue came up during testing.

@GnatalieH we don't have research that I know of.  I honestly can't remember exactly what spurred me to open this ticket, it's been a while. I must have worked on this with Jennifer Strickland (former a11y specialist on our team) since she's mentioned in the description but otherwise all I recall is captured above.

> But increasing the margin between elements too much will break the law of proximity (gestalt principle).

Yes, that's a very good point. We certainly don't want to do that.

**Comment by GnatalieH** [comment]
Thanks @andaleliz. I think if we increase the target area inside the accordion header and increase the margin, slightly, between headers we can achieve the desired 22 px. CC @bkjohnson and @cvalarida
