### ISSUE TITLE
Back Link variation  - Accessibility review

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3237]
## Issue Description
We need to conduct a full accessibility review of the back link component. The component can be viewed in Storybook here: [[storybook]](https://design.va.gov/storybook/?path=/story/components-va-link--back)

original ticket: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2797
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3190

## Tasks
- [ ] Full accessibility review of the component is completed
- [ ] Add descriptions of any issues found to this ticket
    - [ ] If any problems are found, add screen recordings and/or screenshots to comments on this ticket that show the problem.
- [ ] If necessary, discuss any accessibility issues found with the engineer who developed the component
- [ ] Re-review any fixes the developer makes to the component

## Acceptance Criteria
- [ ] Component has been reviewed for accessibility issues
- [ ] Any accessibility issues have been addressed

**Comment by caw310** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3237?planning-poker) with Zenhub @rsmithadhoc

**Comment by rsmithadhoc** [comment]
@caw310 The back link variation looks good with the new a11y testing criteria.

I added an [audit PR](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/3287), but it only covers this variation. Since the site only shows the checklist for the full component, including all variations, I won't merge that yet and audit the other variations as time allows.
