### ISSUE TITLE
Update guidance for disabled buttons

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/vets-design-system-documentation#342]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [ ] Content styleguide
- [x] Component
- [ ] Pattern
- [ ] Utility
- [ ] Other 

## What is the name
Buttons, disabled state

## What is the nature of this update?

- [ ] How to build this component/pattern
- [x] When to use this component/pattern 
- [x] When to use something else
- [x] Usability guidance
- [x] Accessibility
- [ ] Implementation
- [ ] Research insights
- [ ] Package information

## Additional Context

We currently don't provide guidance for disabled buttons.  Disabled buttons come with some a11y problems, including insufficient contrast, increasing cognitive load (people have to figure out why they can't interact with something they expect to be able to interact with), and inability to get focus for screen readers. It would be helpful to include this guidance in our design system, as well as use cases for using them, or choosing something else.

This came up while looking at the search button UX on site search, and [resources and support](va.gov/resources).  I almost filed this as a bug but I don't think the global search button fits with `something in Formation isn't working as expected`.

cc @rtwell

**Comment by CourtneyChambers77** [comment]
Disabled buttons should not be designed in a way that they cannot be read by a screen reader (buttons are not focusable, so the users can't reach them with a keyboard). No need to explain that users with disabilities will face problems with such behavior.
Ensure color contrast is checked minimum requirements if not it will be difficult for users to read or recognize the button.
It’s best not to disable buttons or inputs.
Add some nearby visible help text for the button. This would work for sighted users, but not necessarily for low vision users or blind users using a screen reader.
Add aria-disabled="true” instead of disabled. Programmatically link some contextual help text using aria-describedby="id-of-the-help-text”, use JS to stop click and submit events.

**Comment by k80bowman** [comment]
We're working on this as part of #751. Moving this back to Reviewed/Needs Prioritizing for now, though the work on #751 should resolve this.
