### ISSUE TITLE
VADS Alerts

### ISSUE THREAD

**Issue by BobbyBaileyRB** [department-of-veterans-affairs/vets-design-system-documentation#3420]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

  I noticed we have a role="presentation" attribute within all our alerts for the VADS. From my understanding, in HTML this indicates that an element is purely for presentation and carries no semantic meaning. However, there are p-tags and heading levels inside that div. Additionally, when we apply live regions to it, we're experiencing some strange announcement issues where it's not announcing any content within the presentation.

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/presentation_role

## What I expected to happen

  All content to be announced in multiple situations (unsure if this is causing the problem on our end)

## Reproducing

- Formation version:
- Device Any
- Browser: Any

Steps to reproduce:

1. Inspect the code at https://design.va.gov/components/alert/

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [ ] This bug is blocking work currently in progress
- [x] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

**Comment by BobbyBaileyRB** [comment]
@rsmithadhoc 

Thank you

**Comment by rsmithadhoc** [comment]
Just an update, [this was added](https://github.com/department-of-veterans-affairs/component-library/pull/280) due to an issue with NVDA announcing the alert as clickable. This is due to a click event bubbling up to an element higher up in the DOM. The recommended fix for this from NVDA was to mark it as presentational. I'm looking to see if there's another way to fix that.

**Comment by rsmithadhoc** [comment]
This was originally added in https://github.com/department-of-veterans-affairs/component-library/pull/280, but here I am reverting this change.

"Clickable" will be announced by NVDA if the element has a click handler or an ancestor element has a click handler. In the chain of parent elements and see if "click" is being handled by one of them, it will announce as clickable.

While using presentation role is a workaround, it is common in JavaScript applications to have a click handler higher up the chain. Storybook needed role="presentation" added to its root element to get this fix to work in the past. That had to be disabled for the Storybook upgrade, and I was not able to get it to work in the newer version. Without that added to Storybook, this fix will still say "Clickable" for the alert because there is a click event on the main Storybook div.

Because of that, I believe it can't be fixed at only the component level, it would require parent elements to not have click handlers. It's likely that this problem would arise in other components and elsewhere around the site. I don't think fixing these by adding role="presentational" is sustainable

JAWS changed and turned off clickable announcements by default. NVDA is the only screen reader that announces this by default. I believe they should change the default (Preferences > Document Formatting > Elements > Clickable) to off as well.
