### ISSUE TITLE
Update CSS library design tokens for base, root font and default font

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3452]
## Description
Update CSS library design tokens for base and root font. Base font design token will be changed to root font design token. Root font design token will be set to 16px and default font design token will be 16.96

## Details
Adding design tokens: [Change base font design token and add default font design token ](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3388)
Change the base font design token to root font design token. Set the root font design token 16px.
Add a default font design token for 16.96

## Tasks
- [ ] Add root font and default font design tokens to the CSS library

## Acceptance Criteria
- [ ] New design tokens have been added to the CSS library

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3452?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc

**Comment by jamigibbs** [comment]
Will any [documentation](https://design.va.gov/) need to be updated for this too?

**Comment by jamigibbs** [comment]
> Add a default font design token for 16.96

16.96 is a normalization value specifically for Source Sans Pro. We have other font families on vets-website though. Should the name of this token mention Source Sans Pro?

**Comment by micahchiang** [comment]
A couple of things to add here for discussion: 
1. We have a [vads-font-size-body-medium](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/css-library/dist/tokens/scss/variables.scss#L138) which is likely the token that needs to be renamed to something like `vads-font-size-typography-default` (I dunno naming is hard) 
2. We also have a [v3-font-base-size](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/css-library/dist/tokens/scss/variables.scss#L132) which is the 16px root font size. We may want to consider renaming this as well to something like `vads-font-size-root` 
3. The above are _different_ from the utility classes that get generated, which use [this map](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/css-library/src/tokens/font.scss). The map is built off the _root_ font size, and also generates a list of tokens [here](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/css-library/dist/tokens/scss/variables.scss#L120-L131), where `font-size-base` = 1rem. 
4. We can update token names, but we also need to decided if we're adding a new utility class that sets an element's font-size to 16.96px or 1.063rem (whatever the value is). I mention this because the original discussion in slack was centered around `vads-u-font-size--base` setting font-size to 1rem instead of 1.063rem as some people might expect it to. Instead, a user would currently need to use `vads-u-font-size--md` to achieve 16.96px on an element using a utility class.
