### ISSUE TITLE
Sign in alert accessibility fixes

### ISSUE THREAD

**Issue by rsmithadhoc** [department-of-veterans-affairs/vets-design-system-documentation#3611]
## Description

Issues from a11y review.

## Details

- Font resizing not working on the heading
    - I believe we'll need to use a relative sizing unit for this.
    <img width="870" alt="Image" src="https://github.com/user-attachments/assets/c8ab02f0-0ed0-4463-931b-6bb91173e23a" />

## Tasks
- [ ] Make fixes and test.

## Acceptance Criteria
- [ ] Issues have been addressed.

**Comment by Andrew565** [comment]
Headline font size is currently "fixed" at its current size using pixels, but that's because I copy-pasted the styles from the va-alert stylesheet. There's a comment suggesting it could be changed to 1.33 rem, but we might want design to weigh-in on the appropriate 'default zoom' size?![Image](https://github.com/user-attachments/assets/8efdd5bc-e65c-4196-b6c8-97ba177e0ee8)

**Comment by babsdenney** [comment]
Reviewed the design and it looks good. The header is now using 1.33 rems.
