### ISSUE TITLE
Improve documentation for CheckboxGroup

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/vets-design-system-documentation#373]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [ ] Content styleguide
- [x] Component
- [ ] Pattern
- [ ] Utility
- [ ] Other

## What is the name

`CheckboxGroup`

## What is the nature of this update?

- [ ] How to build this component/pattern
- [ ] When to use this component/pattern 
- [ ] When to use something else
- [x] Usability guidance
- [ ] Accessibility
- [ ] Implementation
- [ ] Research insights
- [ ] Package information

## Additional Context

A team is using `<CheckboxGroup>`  and discovered that it isn't obvious how to programmatically set the `checked` state of each checkbox.

https://dsva.slack.com/archives/CBU0KDSB1/p1610490851433500

First, I looked at the [documentation on Storybook](https://design.va.gov/storybook/?path=/docs/components-checkboxgroup--default) and saw that there wasn't a `checked` option in the Parameters table. However, with a bit of experimentation within the Controls section in the Canvas tab I was able to manipulate the `options` and `values` props to get a check to appear.

This is another example of how Storybook can help teams.

**Comment by jamigibbs** [comment]
The `CheckboxGroup` React component is deprecated in favor of the `va-checkbox-group` web component. Since va-checkbox has a specific `checked` prop with [details in Storybook](https://design.va.gov/storybook/?path=/docs/components-va-checkbox-group--default), I believe the documentation is clear enough now for teams to implement it. Please re-open though if we feel like this should be clearer.

![Screenshot 2023-07-21 at 3 21 41 PM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/1b9b25d0-270d-4272-b945-c2c3b67351eb)
