### ISSUE TITLE
Clarify when to use full-width buttons on mobile

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/vets-design-system-documentation#419]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [ ] Content styleguide
- [x] Component
- [ ] Pattern
- [ ] Utility
- [ ] Other

## What is the name

Buttons
https://design.va.gov/components/buttons

## What is the nature of this update?

- [ ] How to build this component/pattern
- [x] When to use this component/pattern 
- [x] When to use something else
- [ ] Usability guidance
- [x] Accessibility
- [ ] Implementation
- [ ] Research insights
- [ ] Package information

## Additional Context
This question came up in [this accessibility audit ticket](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15086). I'm closing this one and creating a new one to pass the project over to VSP.

**Comment by outerpress** [comment]
This came from a VAOS audit in this ticket: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15086

Moving to VSP and closing that ticket in VAOS.

cc: @caw310 @rtwell @emilywaggoner @laurenernest

**Comment by andaleliz** [comment]
Commenting to give a +1 to this documentation clarification; this question has come up on my team a few times.

**Comment by humancompanion-usds** [comment]
In the past I've done full width with the primary stacked on top and the secondary below it, with sufficient spacing between, until the 480px breakpoint and then split them aligning the primary to the right and the secondary to the left and keeping them pinned to the outside edges of the viewport until a wider viewport pushes them too far apart and you suffer from [Fitts' Law](https://lawsofux.com/fittss-law/), which is why I suspect the USWDS doesn't do this and just pairs them on the left at 480px with the Back or Previous button first.

We're working on Progress Button pairs right now so I will ensure our behavior and guidance are in sync.

* [ ] Ensure button pair buttons are full width until the 480px breakpoint.
* [ ] Ensure guidance indicates width changes for Button and Progress Button pairs.
* [ ] Ensure there is a mobile version of Button and Progress Button in Sketch.
