### ISSUE TITLE
Document Tabs as a Component

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#611]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [ ] Content styleguide
- [x] Component
- [ ] Pattern
- [ ] Utility
- [ ] Other

## What is the name

Tabs

## What is the nature of this update?

- [x] How to build this component/pattern
- [x] When to use this component/pattern 
- [x] When to use something else
- [x] Usability guidance
- [x] Accessibility
- [x] Implementation
- [x] Research insights
- [ ] Package information

## Additional Context

Tabs do not yet exist as a web component. When they do, we should document how and when to use Tabs on design.va.gov under Components.

**Comment by caw310** [comment]
Per meeting with Kevin and Ryan on 1/27, documentation on tabs will be guidance on when to use and alternatives and examples.

**Comment by caw310** [comment]
@GnatalieH , I put this in slack and am adding it here. It looks good. I have one suggestion for the Tabs page. Since it states that Tabs is considered deprecated, I would suggest that we would put usage first and the examples further down on the page. We don’t want to encourage people to use tabs so let’s put examples lower down.
