### ISSUE TITLE
[Modal] Modal Component 1px Offset When Content is Scrollable

### ISSUE THREAD

**Issue by Kwoly** [department-of-veterans-affairs/vets-design-system-documentation#614]
# Bug Report

- [ ] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened
When utilizing the `Modal` component for the va.gov sign in popup, we are seeing a 1px offset where the content box is slightly overlapping the container. 

![image](https://user-images.githubusercontent.com/13320944/147952038-7b4489cc-d793-48e5-8c04-2ed033b1e46a.png)

This is obviously very minimal, but I believe I have tracked the issue down to being a browser render bug with a container utilizing both `overflowY: scroll | auto` & `transform: translateY()`.

I was able to replicate in a codepen (sorry I did not save the link), but here is the screenshot of simple recreated "modal"

Without transform translate
![image](https://user-images.githubusercontent.com/13320944/147952470-141d8b19-d6d3-42d8-b83a-b81e89253c16.png)

With transform translate
![image](https://user-images.githubusercontent.com/13320944/147952668-3725e369-7132-4bb3-b9af-5dd1c14031bf.png)

Notice with the translate, that the content box is now slightly taller than the scrollbar.

## What I expected to happen

Expectation is to not have the 1px offset, and the container perimeter be smooth all around. That said, my initial thought is that this is a browser rendering issue and may not be "fixable" without refactoring the modal to not use `translate`. I have found that adding a 1px white top|bottom border does mask the issue, but is a little hacky and may not be desirable.

If we want to chalk this up to a non issue due to the edge case and how minor the bug is, that is fine as well.

## Reproducing
Reproduced on Windows | MacOs | Android
* Ios untested

Browsers: Safari | Chrome | Firefox

Steps to reproduce:

1. See Va.gov Sign In Modal
2. Resize screen to make the modal content scrollable
3. Notice the content slightly taller than the container box (this is not consistent and sometimes requires screen resizes. It can appear on top, bottom, or both edges)

**Comment by caw310** [comment]
Check to see if this is still an issue. Modal was recently updated so may not be a problem.

**Comment by jamigibbs** [comment]
**Analysis**

- I was able to reproduce the issue from the login modal at https://www.va.gov/?next=loginModal and the [React version in Storybook](https://design.va.gov/storybook/?path=/docs/components-modal--default) (the React version is being used in the login modal).
- I was only able to reproduce the issue by adding a wrapping div to the modal content with a background color. For example in the login modal, the following CSS is applied. This is what is making the small gap visible.

```
.login {
    background: #fff;
}
```
- I was not able to reproduce this issue in the [web component](https://design.va.gov/storybook/?path=/docs/components-va-modal--default) version in Storybook since the scrolling behaves slightly different with the content scrolling up/down the page instead of up/down the modal container.

**Recommendation**

This should be resolved when the login modal is replaced with the [web component version.](https://design.va.gov/storybook/?path=/docs/components-modal--default)

Since the React component has been deprecated, we will not be addressing the issue with the design system component but for completeness, [the custom background color applied to the `.login` class](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/user-nav/sass/user-nav.scss#L203) can be removed and it would appear seamless.

Alternately, I would agree with the reporter that adding an `outline` or border to the modal body and/or inner content would make the content appear seamless as well. `outline: 1px solid #ffffff;`
