### ISSUE TITLE
[Breadcrumb] Experimental design: Breadcrumb "home" segment label change

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/vets-design-system-documentation#638]
Check the [design system backlog](https://design.va.gov/documentation/backlog) and [experimental design tab](https://design.va.gov/experimental-design/) to see if your proposal has already been suggested. 

## What
Modification to the "home" link label in the standard breadcrumb from "Home" to "VA.gov home"

## Why
Explain why you think this should be added to the VA.gov design system.
> - Participants in early research on VAMC sites showed some confusion around where the "home" link in the breadcrumb would take them.  The "home" link was confused with the health care system link in the breadcrumb.  Because of this issue, the VAMC sites eliminated the "home" link from the breadcrumb, relying on the VA logo to return users to the home page of the site. 
> - The Vet Center mini sites added the "home" link back into the breadcrumb component, however they changed the language from "home" to "VA.gov home" so it would not be confused with the main Vet Center landing page. 
> - This issue is to formalize that this variation of the component is alread in production.
> - The Facilities team is planning to gather some feedback on this change in an upcoming research effort. 

## Next steps
You may present your work to the Design System Council at an upcoming meeting. If you do not or cannot attend the Design Council Meeting, you can opt to get an asynchronous approval. 

Submit requests to join an upcoming Design System Council meeting in #vsp-design-system.  

During the meeting, the Design System Council Working Group will evaluate the request and make a decision. 

If your request is approved, you can add your component/pattern to the [Experimental Design section](https://design.va.gov/experimental-design/) of design.va.gov. If you have any questions on how to add your component/pattern to the Experimental section, please reach out to the Design System Team at #vsp-design-system.

**Comment by bkjohnson** [comment]
I'm just adding a bunch of context here for future discussion since this seems like an experimental use of an existing component rather than a proposal to _create_ an experimental component. This seems like it could be accomplished by updating usage guidance based on the research results and then implementing that guidance across the site.

## App code

In application code teams can already put "Va.gov home" as the first breadcrumb link if they want to - the "Home" text isn't hardcoded into the component. Here's an example with the react component:

<details>

!["VA.gov home" as first link in React breadcrumb component](https://user-images.githubusercontent.com/2008881/152068582-3c70503f-9e7b-48b8-9313-3511120c2575.png)
</details>

And here's one with the new web component:

<details>

!["VA.gov home" as first link in Web Component breadcrumb](https://user-images.githubusercontent.com/2008881/152068672-70302b03-4afb-4e33-94c2-741b6686ddb9.png)
</details>

Here are some examples of teams using "Home" as the first item:

- [`vaos`](https://github.com/department-of-veterans-affairs/vets-website/blob/44909dfa7bbab8d6dd92085bffb45e85778cd662/src/applications/vaos/components/Breadcrumbs.jsx#L7-L10)
- [`disability-benefits`](https://github.com/department-of-veterans-affairs/vets-website/blob/44909dfa7bbab8d6dd92085bffb45e85778cd662/src/applications/disability-benefits/2346/containers/App.jsx#L22-L23)

## Static content

In the content templates an  update could be made here:

- [`src/site/includes/breadcrumbs.html`](https://github.com/department-of-veterans-affairs/content-build/blob/28a1f0379885e05c6a81b1453e844ff6cfc547bf/src/site/includes/breadcrumbs.html#L8-L10)

There's [this other breadcrumbs template](https://github.com/department-of-veterans-affairs/content-build/blob/28a1f0379885e05c6a81b1453e844ff6cfc547bf/src/site/includes/breadcrumbs.drupal.liquid#L27-L39) which is setting the text of the first item based on what's coming from the CMS.  There's also an on override there which is how "VA.gov home" is getting added in the [`vet_center`](https://github.com/department-of-veterans-affairs/content-build/blob/28a1f0379885e05c6a81b1453e844ff6cfc547bf/src/site/layouts/vet_center.drupal.liquid#L3-L5) and [`vet_center_locations_list`](https://github.com/department-of-veterans-affairs/content-build/blob/28a1f0379885e05c6a81b1453e844ff6cfc547bf/src/site/layouts/vet_center_locations_list.drupal.liquid#L3-L4) templates. There's not much to go off of in the [original PR](https://github.com/department-of-veterans-affairs/content-build/blob/28a1f0379885e05c6a81b1453e844ff6cfc547bf/src/site/layouts/vet_center_locations_list.drupal.liquid#L3-L4) and its linked issue, but I don't think the `customHomeCrumbText` override would be necessary if content was updated.

**Comment by mnorthuis** [comment]
Oooo, I didn't think about new component vs variation of existing component. Could be good to discuss the right process if the experimental design process is not the right pathway. 

My goal with this, was to document that there's a variation out there that the team is hoping to test.  If that test goes well, discuss making this the standard and rolling it out across the site.

**Comment by caw310** [comment]
@mnorthuis , This is on the agenda for the DSC meeting tomorrow Feb 4.

**Comment by artsymartha68** [comment]
Is the current/proposed spelling "VA.gov home" or "Va.gov home"?

**Comment by mnorthuis** [comment]
@artsymartha68 will look for content to make the recommendation on that.

**Comment by artsymartha68** [comment]
Thanks @mnorthuis I have seen it both ways in this ticket so I was curious. I figured you'd be ON IT.

**Comment by bkjohnson** [comment]
I apologize for causing confusion - the current spelling is "VA.gov home".

![image](https://user-images.githubusercontent.com/2008881/152417841-f7fe3f08-780a-4e56-8cb7-8b845abd1425.png)

**Comment by mnorthuis** [comment]
I believe it will be VA.gov, but the content team has enlightened me many times :-)

**Comment by artsymartha68** [comment]
We'll just need to make sure it sounds right read aloud. "V-A" instead of "vah".

**Comment by mnorthuis** [comment]
Exactly!

**Comment by caw310** [comment]
Action items from DSC meeting on 2/4 
* Follow up on timing of study (Mikki)
* Make sure breadcrumb is read as VA.gov. 
* From engineering perspective, what ever solution, it should be a solution that is difficult to break so teams cannot change breadcrumb.

**Comment by humancompanion-usds** [comment]
@mnorthuis or @bkjohnson - We're trying to clean up our backlog of DSC requests. Can either of you update us on the status of this work? Thanks.

**Comment by mnorthuis** [comment]
The facilities test we were hoping to use to test this did not happen due to contract changes, and now is no longer planned.  I will dig around to see if I can find either data to use for this, or if there's another usability test I can sneak a question into...

**Comment by mnorthuis** [comment]
FWIW, we are moving in this direction on a few fronts and feel strongly this provides needed clarity in places where we have sort of mini experiences built into VA.gov (i.e. facility sites, MHV portal, etc).  I will also look for additional opportunities to gain feedback in the MHV work.

**Comment by caw310** [comment]
Did this get tested?

**Comment by humancompanion-usds** [comment]
Mikki and I decided to go forth with this. It's already in place on Vet Center pages, and will be with MHV very soon. Thus I'd like us to update this in Figma and in the web-component.

**Comment by humancompanion-usds** [comment]
@caw310 - Please create a ticket for updating Breadcrumb home in Figma to VA.gov. Then let's use this ticket for the web-component update. Thanks!

**Comment by caw310** [comment]
Here is the ticket to update FIgma. https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2419

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/638?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by mnorthuis** [comment]
"VA.gov home" should be the standard, not something that teams have to add.  Ideally, in our benefit world, teams shouldn't be changing that text at all.

**Comment by jamigibbs** [comment]
Hi @mnorthuis I apologize I should have articulated further the complication by programmatically forcing that label.

I think the key issue is that we have concerns that the breadcrumb component could be used in two scenarios where we would not want to force this label: 

1. a situation where the first link is _not_ going back to the root of VA.gov
2. the component is not being used on VA.gov at all

An example of the first scenario in the secure messaging app:

![Screenshot 2024-02-23 at 12 10 24 PM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/2fff915b-2acb-47e6-bf96-801d5ada19d7)

I'm not sure the reason why this team is needing to use `va-breadcrumbs` in this way but it does exist at the moment.

cc @humancompanion-usds

**Comment by jamigibbs** [comment]
Thanks @mnorthuis. We have made "VA.gov home" default for the first label inside the component itself with the ability to override it using the prop `home-veterans-affairs` (boolean). Where teams need to override the default behavior, that can set that prop to `false`.

https://design.va.gov/storybook/?path=/docs/uswds-va-breadcrumbs--default
