### ISSUE TITLE
Document how to display downloadable PDFs

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/vets-design-system-documentation#647]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [ ] Content style guide
- [ ] Component
- [x] Pattern
- [ ] Utility
- [ ] Other

## What is the name?

We have a lot of downloadable PDFs on va.gov and different teams use different patterns (buttons, links, size of file). We do not have any documentation for designers/developers to know how a downloadable PDF should look. 

## What is the nature of this update?

- [x] How to build this component/pattern
- [x] When to use this component/pattern 
- [x] When to use something else
- [x] Usability guidance
- [x] Accessibility
- [ ] Implementation
- [ ] Research insights
- [ ] Package information

## Additional Context

Different examples are on [find a form](https://www.va.gov/find-forms/?q=1010) and VA letters.

**Comment by GnatalieH** [comment]
This may be a Content style guide issue, as well. I've talked to @RLHecht about download link text, CCing her for awareness. The USWDS includes guidelines under their [Links documentation](https://designsystem.digital.gov/components/link/) on how to display PDF download links:

> Show file type and size for links to non-HTML content. When possible, create HTML pages instead of linking to files like PDFs. If you do link to a file, tell users ahead of time if the link may trigger a file download, and show the size and format of that file.
> 
> We recommend including this information at the end of the link, in the format [FILE_TYPE, SIZE]. We recommend using the file type rather than a product name. Use uppercase for the file type and a comma for the separator. For file size, use the number of pages in the document or the size in MB or KB if the document is not paginated.
> 
> Example 1:
> 
> GSA published a report, [Transforming the American Digital Experience [PDF, 18 pages]](https://designsystem.digital.gov/files/next/Transforming-the-American-digital-experience.pdf)
> 
> Example 2:
> 
> Download the [Revised 508 Standards Applicability Checklist [DOCX, 2 pages]](https://section508.gov/sites/default/files/Revised%20508%20Standards%20Applicability%20Checklist%20%287%29.docx)
> 
> Example 3:
> 
> Download the [USWDS 2.11.2 Design Kit for Sketch [ZIP, 13.3 MB]](https://github.com/uswds/uswds-for-designers/releases/download/v2.4.0/uswds-for-designers-v2.4.0.zip)

**Comment by RLHecht** [comment]
Thanks @GnatalieH. Our current guidance in the [style guide](https://design.va.gov/content-style-guide/links) is to put the file format in parentheses at the end of the link. We also often use the word "download" in the link language, though not always. I did bring up adding the size of the file to Beth and Danielle after we talked, and we were going to discuss it further. 

This links page still needs to be reworked since some of the information we have in here is outdated. We are now avoiding sighted language and making sure that every link has a target and a purpose, for example.

**Comment by GnatalieH** [comment]
Thanks @RLHecht, I appreciate the reply. I have a [PR for the Links component documentation](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/GnatalieH-patch-2/src/_components/links.md) created which "links" (lol) to your documentation in the Content style guide. I'm just waiting until the Links code preview gets fixed to make it live. @allison0034 I called out PDF links in the Links documentation. I can update my guidance if necessary.

**Comment by Mottie** [comment]
Related ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/11852

> Download PDF Link Example
> ```html
> <a 
>   href="https://www.va.gov/playbook/downloads/Voices_Of_Veterans.pdf" 
>   download="Voices_Of_Veterans.pdf" 
>   type="application/pdf">
>     <i aria-hidden="true" class="fas fa-download vads-u-padding-right--1" role="img"></i>
>       Download the Voices of Veterans <dfn><abbr title="Portable Document Format">PDF</abbr> (4.9<abbr title="Megabytes">MB</abbr>)</dfn>
> </a>
> ```

**Comment by KevinMHoffmanUSDS** [comment]
@bethpotts

**Comment by caw310** [comment]
@GnatalieH this is a stretch goal for sprint 73 (March 3-15).

**Comment by GnatalieH** [comment]
Per Kevin's suggestion, we are going to recommend the following format for PDF download links:

fa-download icon + 8px margin + Download link text (PDF)

In the case of translated PDFs, the language abbreviation should go after the file type in parentheses, like this:

fa-download icon + 8px margin + Download link text (PDF, esp)

Closing this ticket because the PDF download link guidance is addressed in the Links (component) documentation I'm writing.
