### ISSUE TITLE
Update Sketch VA Pattern library to match developed components

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#675]
### Steps to complete

1. Refer to results of audit in [#674](https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/674).
2. Update Sketch symbols to match developed components. Or, in cases where components should be altered, make tickets for fixes.

### Progress Checklist

* [x] Accordion
* [x] Additional info
* [x] Address block
* [x] Alert Boxes
* [x] Alert - Expandable
* [x] Back to top
* [ ] Banner
* [x] Breadcrumbs
* [x] Button
* [x] Card
* [x] Copy deep link
* [x] Divider
* [x] Featured content
* [x] Header & Footer
* [x] Link
* [x] Link - Action
* [x] Loading indicator
* [x] Modal
* [x] OMB info
* [x] On this page
* [x] Pagination
* [x] Process List
* [x] Progress bar - Activity
* [x] Progress bar - Segmented
* [x] Promo banner
* [x] Sidenav
* [x] Tabs
* [x] Tag
* [x] Telephone

#### Form controls
* [x] Text inputs
* [x] Select box
* [ ] Checkbox
* [ ] Radio buttons
* [x] Date input
* [ ] Number input
* [ ] Input message

**Comment by humancompanion-usds** [comment]
We've done 12 and have 25 to go. So roughly 1/3rd of the way there after 2 sprints. A few of these components (header, footer, card) are not in design.va.gov yet but are on the way. A few of these just recently got promoted form experimental and thus don't exist in Sketch at all.

**Comment by seanasewell** [comment]
Completed the following...

- [x] Tag
- [x] On this page (jump links)
- [x] Radio button
- [x] Checkbox
- [x] Number input

The ones remaining need symbols.

**Comment by GnatalieH** [comment]
@seanasewell what is the left and right padding we're recommending around the text label in the Tag component? I was just wondering after looking at the example in Sketch, which shows the text layer stretched the width of the background with centered text. Thanks.

**Comment by seanasewell** [comment]
> 

This component was already made in Sketch. I assumed it was correct since it was already a part of the library. So I just moved it over to it's own page. Sorry for the oversight! But I agree with your recommendations. I'll make all of the obvious updates now besides the font (until we can narrow down specific specs for that).

Components I have created that need review:

- On this page (jump links)
- List pagination

Components I have started reviewing however need some discussion:

- Checkboxes
- Radio buttons
- Number inputs
- Tags

**Comment by caw310** [comment]
Matt will review the updates that have been made. We will close out as many as possible by the end of the sprint then close this ticket and write up new tickets for the remaining ones which are either more complex or lower priority to be done in future sprints.

**Comment by caw310** [comment]
@humancompanion-usds please review 
- Checkboxes
- Radio buttons
- Number inputs
- Tags

**Comment by humancompanion-usds** [comment]
@seanasewell - Looks good. Feedback: To my understanding, it is not currently possible to disable a checkbox (at least, that is what Storybook is telling me). There is a request from the a11y folks that we not make it possible. Thus we should not show a disabled state for checkboxes and radio buttons.

* Archive disabled states for checkbox and radio buttons.
* Margins:
  * Checkbox symbols have 14px below them. In fact they should have 12px above them and be aligned to the bottom edge of the artboard because that's how they are coded. Essentially, our labels have 12px of margin-top. This is so when you stack them they are appropriately spaced.
  * Radio buttons. Currently have 14px below (unselected variation) and should have 10px above.
  * Number input: 24px in Sketch but should have 30px margin-top (!? not sure why it's so much but, that's how it is coded)

**Comment by GnatalieH** [comment]
- Promo banner is being handled by [ticket #914](https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/914).
- Expandable alert is being handled by https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/1010
- Link - Deep content should be re-examined because it's an experimental component. Was the experiment a success?
- Tabs are a deprecated component so I don't think we need Sketch assets unless we un-deprecate it.
- I'll write tickets for the other remaining items: Banner, Divider, and Sidenav.

CC @caw310 and @humancompanion-usds

**Comment by seanasewell** [comment]
> @seanasewell - Looks good. Feedback: To my understanding, it is not currently possible to disable a checkbox (at least, that is what Storybook is telling me). There is a request from the a11y folks that we not make it possible. Thus we should not show a disabled state for checkboxes and radio buttons.
> 
> * Archive disabled states for checkbox and radio buttons.
> * Margins:
>   
>   * Checkbox symbols have 14px below them. In fact they should have 12px above them and be aligned to the bottom edge of the artboard because that's how they are coded. Essentially, our labels have 12px of margin-top. This is so when you stack them they are appropriately spaced.
>   * Radio buttons. Currently have 14px below (unselected variation) and should have 10px above.
>   * Number input: 24px in Sketch but should have 30px margin-top (!? not sure why it's so much but, that's how it is coded)

Sorry, I didn't actually design these. Since they already had states, I figured they were already good to go and just moved them over to the page that designers reference. Oversight on my end! I'll take a look at all of these today to ensure they are parallel to what is in Storybook.

**Comment by humancompanion-usds** [comment]
I took care of a number of things yesterday evening and starred the release:
- Removed “Foundation, Components, Patterns” page as all elements are now on distinct pages so that we can link to them from design.va.gov. This required the following changes:   
  - “Conditional fields” is now on Patterns - Forms and will be re-evaluated.  I think our guidance is okay but we should get DK's document into a Forms pattern on how to do progressive disclosure properly. It's not great that this guidance is only in Sketch. 
  - “Featured story” is, for the moment, archived and will be re-evaluated.   I'm 99% sure the Content team doesn't want the Featured Content component to be used in this way. But it is present on Facility pages. I just need to check with them to see if it should remain archived. 
- Add new “Show more options” pattern. Just deployed the new pattern a few minutes ago.
- Renamed remaining _building-blocks symbols and Global Components symbols to be associated with their appropriate components.

I will file an issue for the Conditional fields. Once Natalie finishes up filing issues we can close this.

**Comment by seanasewell** [comment]
I made updates to Checkbox, Radio Button, and Number Input. Ready for review @humancompanion-usds @GnatalieH

**Comment by humancompanion-usds** [comment]
@seanasewell - Checkbox and radio button looked good. I fixed one little alignment issue with the error text and label to left align them. One little nit to fix up on Number Input: It looks like the border in the error state drops down below the input by 8px so the overall component is a bit taller in that error state. Otherwise these are good to go.

**Comment by caw310** [comment]
Closing as we have addressed most issues or have written tickets for the remaining items that require more time and coordination.
