### ISSUE TITLE
[Modal] Unequal margins on va-modal component (WC and react version)

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/vets-design-system-documentation#693]
# Bug Report

The va-modal-body div on the va-modal component appears to have a margin-right of 2rem and none on the left. This has made the va-featured-content component in our modal content appear with more white space on one side than the other.

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

![Screen Shot 2022-04-08 at 3 02 23 PM](https://user-images.githubusercontent.com/8332986/162780809-637ac680-4173-4864-bec5-e93f7d97c278.png)

This occurs when using the va-featured-content component, but I would imagine it would happen with any element that spans the entire width of a va-modal. It was only really noticeable because the va-featured-content component has a colored background.

Here is a codesandbox example in isolation, mostly because I wanted to make sure no other CSS styles could be causing the issue.

https://codesandbox.io/s/va-react-sandbox-cwrd9m?file=/src/App.js

## What I expected to happen

Even margin on the left and right of the modal content.

## Reproducing
- Formation version: newest version, I believe 7.0.0
- Device: Macbook pro
- Browser: Firefox and Chrome

Steps to reproduce:

1. Create a va-modal
2. Add va-featured-content component to the modal content and fill with placeholder text
3. Open modal and view margins.

**Comment by jamigibbs** [comment]
@GnatalieH Can you confirm if this margin is intentional? Here is a mock-up of a modal that includes various full-width content items (including the `va-featured-content` component mentioned above):

![Screen Shot 2022-09-23 at 12 49 08 PM](https://user-images.githubusercontent.com/872479/192027871-dd0b3fd0-72a6-49e0-976a-858adb16e7bd.png)

I've looked through our [Sketch Modal component examples](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/symbols?g=Modal) and the closest one I can find that shows full-width content is the privacy-act-statement modal which _does_ show the content lining up to the left of the close button:

![Screen Shot 2022-09-23 at 12 49 18 PM](https://user-images.githubusercontent.com/872479/192028070-0b353d62-f0e2-47a2-8416-202a8beddbe0.png)

So I suspect that the margin discrepancy mentioned in this issue is intentional and likely not something we will change but I wanted to double-check with you first before closing.

**Comment by GnatalieH** [comment]
Hi @jamigibbs. Yes, the above margin is intentional. I wasn't the one who designed it that way, but it's consistent with how other modals look.

**Comment by caw310** [comment]
Closing as this is intentional.
