### ISSUE TITLE
Investigate separating Symbols into their own file to be imported by Pattern Library

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#883]
This issue tracks the work to investigate splitting out our Symbols into their own protected file that would be editable only by Natalie, Sean, and I. The Pattern Library would then consume that Symbols file. We just need to verify that users of the Pattern Library would still have access to Symbols in their project design files.

**Comment by caw310** [comment]
What would it take to do this. Do a test to see what is required.

**Comment by seanasewell** [comment]
@GnatalieH @humancompanion-usds I have been testing this and here is what I have learned.

Keeping the components in the same file as the symbols is problematic for more reasons than we initially thought. It turns out that copying and pasting the components from the parent symbol file into a working file stores the component as a local file symbol ([see example](https://d.pr/i/naxTye)). This might confuse designers as their file becomes larger and larger. They might accidentally use their local symbol library instead of the va.gov symbols library. The fix in that scenario is for the designer to replace the newly pasted local component with the va.gov library component and then remove the local symbol and styles that snuck into their working file ([see example](https://d.pr/i/fObQjL)). That process seems like a headache.

Proposed solution:

Create a new file that will house all of the components. This will be separate from the va.gov symbols library. I have already started this ([see file](https://www.sketch.com/s/22985931-dcb6-45d2-8abd-2e32b77497a6)). In order to ensure that the components aren't local symbols I will have to add all of the components from the va.gov symbols library manually. This will enable designers to copy directly from this file and paste into their working file without having to worry about accidentally creating local symbols in their working file ([see example](https://d.pr/i/VK491b)). Since the components will live in a new file, my assumption is that the URL of the components will change. Therefore, design.va.gov pages where a Sketch component page is referenced will need to be updated as well.

Let me know if you need me to clarify anything. I can keep working on this file if you would like and once completed, create a list of all the updated component page URLs.

cc @caw310

**Comment by seanasewell** [comment]
@GnatalieH 

_> So, will Designers open up the component file that's in the Design Team workspace to do their copy and pasting, if that's how they want to work?_

Yes, they will be able to open up the component file and copy and paste components into their working file. They will still need to connect the va.gov symbols library to their working file so that their working file knows what master symbol file to reference.

_> And, will Designers need to add a new library to their prototypes for the symbols, if they want to work via the symbol insert menu?_

Yes, if they prefer to insert components using the insert menu, they can do that method as well (as long as they connected the va.gov symbols library to their working file of course). Nothing will change in regards to the va.gov symbols library. That file will remain the same. Except we will be able to lock it so only specific people can access it.

**Comment by seanasewell** [comment]
After discussing with @GnatalieH here are next steps

- Continue to insert and format symbols from Sketch library into new component file located in the Design Team workspace. Designers will be able to copy and paste from this file into their working file without having to worry about accidentally adding local symbols. And DST won't have to worry about designers working from within the library file.
- After all symbols are added to the new component file, we can lock the library file and only make it accessible for DST.
- After all symbols are added to the new component file, we will need to create a list of all of the new URLs of each component page and update each component page on design.va.gov to reflect the change. 

@caw310 How do you prefer making tickets for stuff like this? Would you like me to create it and add a description and acceptance criteria or is that something you want to do?
