### ISSUE TITLE
Button pairs - Accessibility review

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#941]
## Issue Description
We need to conduct a full accessibility review of the Button pairs component. The component can be viewed in Storybook here: https://937-button-pair--60f9b557105290003b387cd5.chromatic.com/?path=/docs/components-va-button-pair--default

## Tasks
- [ ] Full accessibility review of the component is completed
- [ ] Add descriptions of any issues found to this ticket
    - [ ] If any problems are found, add screen recordings and/or screenshots to comments on this ticket that show the problem.
- [ ] If necessary, discuss any accessibility issues found with the engineer who developed the component
- [ ] Re-review any fixes the developer makes to the component

## Acceptance Criteria
- [ ] Component has been reviewed for accessibility issues
- [ ] Any accessibility issues have been addressed

**Comment by davidakennedy** [comment]
# Feedback

I've reviewed this component, and don't have much feedback. As a reminder, here's the feedback framework we use when doing accessibility audits.

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements

### Should

**Remove unneeded ARIA labels**

The buttons in the demo have visual labels, and also labels added with ARIA through `aria-label`. The use of ARIA here is redundant since the labels are the same as the visual ones. They can be removed. It's still good to have the option of having them in cases where they're needed. But we should discourage cases where visual and ARIA labels are identical.

cc: @k80bowman @bkjohnson

**Comment by andresriveratoro** [comment]
Thank you for helping us out with this one, @davidakennedy.
