### ISSUE TITLE
Anchor text is wrapping on va-on-this-page

### ISSUE THREAD

**Issue by andresriveratoro** [department-of-veterans-affairs/vets-design-system-documentation#951]
## Description
The anchor text on va-on-this-page is wrapping on all breakpoints. This is happening because there is a max-width set on the anchor. We should consider removing the max-width to prevent the text from wrapping when there is available space to fit on the same line. This was brought to our attention by @taylorkaren.

![Screen Shot 2022-06-15 at 17.04.00.png](https://images.zenhubusercontent.com/617ff9ad86edf726772188b8/a4614c0c-7786-480f-9c46-896c3638ae62)
![Screen Shot 2022-06-15 at 17.05.17.png](https://images.zenhubusercontent.com/617ff9ad86edf726772188b8/5b8e19be-8ec0-4de6-a645-46d4d2768ae9)

Currently:
![Screen Shot 2022-06-15 at 17.08.55.png](https://images.zenhubusercontent.com/617ff9ad86edf726772188b8/9dd98da8-9d50-4bd5-80a2-2304fd1e369e)

Without a max-width:
![Screen Shot 2022-06-15 at 17.09.08.png](https://images.zenhubusercontent.com/617ff9ad86edf726772188b8/bc30089d-8499-49f5-887f-5d297dfd157b)

## Tasks
- [ ] Remove max-width from `va-on-this-page` anchors

## Acceptance Criteria
- [ ] Anchor text in va-on-this-page does not wrap when there is available space to fit on the same line

**Comment by sshein** [comment]
The wrapping here is intentional so that users don't have to scan far to read these. However, the DST could review to make sure they feel the width is correct or if they think it should be slightly wider

**Comment by bkjohnson** [comment]
Some more details on the intentionality:

- [Slack thread in public DST channel](https://dsva.slack.com/archives/C01DBGX4P45/p1659036259635199)
- [More details in a private thread](https://dsva.slack.com/archives/G01BJ3ESXL4/p1659041505621359)

**Comment by mnorthuis** [comment]
@humancompanion-usds I've had a couple of questions related to this come up recently and I see this ticket is still open.  Is the wrapping of this component expected? I don't see reference to width within the uswds version but I may be missing it.

**Comment by humancompanion-usds** [comment]
@mnorthuis - I choose not to align to the [USWDS component ](https://designsystem.digital.gov/components/in-page-navigation/) here because they place it in the right-rail, which the a11y CoP is against for users who magnify the page (it would be marooned off screen). Thus there is no v3 version and we haven't been focused on v1 component bugs. It should be set to a reasonable [line length token](https://designsystem.digital.gov/design-tokens/typesetting/measure/). I'd be okay with bumping this up to 68ex. Some text is going to wrap at some point.

**Comment by mnorthuis** [comment]
Thanks for the background.  I don't see this as high priority, so looking at it when the V3 component work is happening would be fine.  Understand that some wrapping will still occur, but in some cases the current width is creating a lot of wrapping given our more conversational tone, H2s can be a bit longer.

**Comment by danbrady** [comment]
> I choose not to align to the [USWDS component ](https://designsystem.digital.gov/components/in-page-navigation/) here because they place it in the right-rail, which the a11y CoP is against for users who magnify the page (it would be marooned off screen).

@humancompanion-usds Pardon my well-intention rabble-rousing...

Does "marooned off screen" mean the right rail gets bumped to the bottom (like in a mobile/responsive view), or does it get cut off somehow horizontally? If it's the first, that should be the expected behavior, right? If we wanted that nav to positioned at the top of the content on mobile/zoomed screens that can be done with media queries and/or CSS flexbox/grid. Or, that right rail can be hidden completely as it's "progressive enhancement" navigation and not essential to the content. (This what the USWDS site does.) Now if it's the latter, than that's an implementation error, no? Do we have anything documented about this decision?

**Comment by humancompanion-usds** [comment]
@danbrady - Good questions. Take it up with the accessibility CoP. My understanding is that they are dead set against a right-rail of any sort and would like to remove them from our Hub pages.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/951?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rsmithadhoc

**Comment by Andrew565** [comment]
FWIW, just increased the max-width to 372px. This ticket is now either obsolete or it needs to be better defined what the desired outcome should be.

**Comment by humancompanion-usds** [comment]
@Andrew565 - This is the desired end state:

> It should be set to a reasonable [line length token](https://designsystem.digital.gov/design-tokens/typesetting/measure/). I'd be okay with bumping this up to 68ex.

**Comment by micahchiang** [comment]
We don't currently have a line length token in code. What we probably need to do here is create a `line-length.json` file in [this directory](https://github.com/department-of-veterans-affairs/component-library/tree/main/packages/css-library/tokens) and populate it the `vads-size-line-length-` tokens [we have here in guidance](https://github.com/department-of-veterans-affairs/component-library/tree/main/packages/css-library/tokens). Then, we'll likely want to import the tokens into our [on this page stylesheet](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/web-components/src/components/va-on-this-page/va-on-this-page.css) and update the max-width to use whatever token we'll need, which in this case seems like `vads-size-line-length-4`

**Comment by caw310** [comment]
Blocked by https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3404

**Comment by caw310** [comment]
Once #3404 is done, replace max width with line length token.
