### ISSUE TITLE
Add link support to VaCheckBox

### ISSUE THREAD

**Issue by bjmccotter7192** [department-of-veterans-affairs/vets-design-system-documentation#961]
# Support question

[Link to slack conversation](https://dsva.slack.com/archives/C01DBGX4P45/p1655836583744179)

- [ ] I’ve searched for any related issues/questions on github

## How can we help?

FLT is trying to add a `<a>` link to the label of a checkbox and the current web component only supports `string` types.

The older [Checkbox React Component](https://design.va.gov/storybook/?path=/docs/components-checkbox--default) allows for either `string` or `object` and I think that would do the trick for our use case as well.

## What you have tried:

Attempted to use the `description` but does not place the text in the right location.

## What problem does this solve?

This will allow for custom HTML to be placed inside of the label.

## Additional Context
![image](https://user-images.githubusercontent.com/22844722/174897494-e3c7201c-dac9-4da0-897d-35dbc4d3e0bb.png)

**Comment by taylorkaren** [comment]
Can you still use the checkbox label to toggle the checkbox selection if a link is embedded in the label text? If you can't, that is an accessibility violation.
Matt: May need to look at a different pattern. There is a description that can go below the check box, maybe that is a better way to handle this use case. May be able to have Sean Sewelll and Martha Wilkes work out what to do here.

**Comment by davidakennedy** [comment]
@artsymartha68 asked me to look into this ticket. Here are a few notes on this pattern:

> Can you still use the checkbox label to toggle the checkbox selection if a link is embedded in the label text? If you can't, that is an accessibility violation.

- I wouldn't classify this as a WCAG violation. The link is still findable for screen readers on the page via text browsing and in the list of links that can be surfaced.
- However, screen readers that use forms mode (JAWS, NVDA), which allow users to traverse and fill out forms more quickly won't notify users that the label that a link inside of it when landing on the checkbox. Screen readers will announce the label text, but not announce that items are interactive within it. Neither does VoiceOver on desktop.
- So not completely inaccessible, but not a great experience either. A better approach might be a pattern that visually has the link above the checkbox, tightly associated to checkbox with proximity. That way, a screen reader will get to it _before_ the checkbox if navigating linearly. Having the link below the checkbox would be better than in the label, but not as ideal as above because of linear navigation. The user would get to the checkbox and be asked to confirm before the opportunity to click on the link to read the privacy policy.

**Comment by caw310** [comment]
@seanasewell , can you provide guidance on this?

**Comment by seanasewell** [comment]
I think @k80bowman has the right idea here. Use [va-checkbox with descriptive JSX](https://design.va.gov/storybook/?path=/docs/components-va-checkbox--default#with-description-jsx) to enable the user to read the privacy policy before clicking on the checkbox. Description could say "Please read our privacy policy (text linked) for information on..." followed by the checkbox with some confirming language similar to what's already there. 

@k80bowman This support ticket references the deprecated checkbox component. Is that why they are having trouble placing the description in the right location?

**Comment by k80bowman** [comment]
@seanasewell thanks for looking into this and confirming that using the description to add the link instead of placing it in the label is the right way to go here. The problem was that they were not able to add that link to the label using the va-checkbox web component the way it is in the form currently. We are asking @bjmccotter7192 to format that checkbox component differently than the way it is in prod currently.

Since it sounds like we are all in agreement that we should not add the capability to add links to the checkbox label to this component, is everyone all right if we close this ticket? @bjmccotter7192 @caw310 @taylorkaren

**Comment by taylorkaren** [comment]
I've added notes about this guidance to the original VAFSC ticket (https://app.zenhub.com/workspaces/forms-library---platform-spike-team-61b0ae1f2cd3c30014e8a5b0/issues/department-of-veterans-affairs/va-forms-system-core/418), so I am good with closing this ticket as well.

If we run into any other issues, we will open a new ticket.

**Comment by GnatalieH** [comment]
@taylorkaren did your team change the copy around so the link is in the description text and not in the checkbox text? Sorry if this question is redundant, I may have mentioned this in Slack as well.
